### ISSUE TITLE
Cannot 'make' 

### ISSUE THREAD

**Issue by sfkaos** [jcampbell05/xcake#101]
Hello,
This seems like a pretty awesome framework. However, I'm currently not able to run `xcake make` on my XCode project.

My current environment is as follows:
XCode version: 7.3.1 (7D1014)
Ruby 2.1.2 (rbenv) 
rbenv 0.4.0

Gems:
*** LOCAL GEMS ***

aasm (4.2.0)
actionmailer (4.2.5.1)
actionpack (4.2.5.1, 4.2.3, 4.2.0, 4.1.8, 4.1.0)
actionpack-action_caching (1.1.1)
actionpack-page_caching (1.0.2)
actionview (4.2.5.1, 4.2.3, 4.2.0, 4.1.8, 4.1.0)
active_attr (0.8.5)
active_model_serializers (0.9.0)
active_utils (2.2.3)
activejob (4.2.5.1)
activemerchant (1.46.0)
activemodel (4.2.5.1, 4.2.3, 4.2.0, 4.1.8, 4.1.0, 3.2.21)
activerecord (4.2.5.1)
activerecord-deprecated_finders (1.0.4)
activerecord-session_store (0.1.1)
activeresource (3.2.21)
activesupport (4.2.5.1, 4.2.3, 4.2.0, 4.1.8, 4.1.0, 3.2.21)
acts-as-taggable-on (3.5.0)
acts_as_list (0.6.0)
addressable (2.3.8)
akami (1.2.2)
american_date (1.1.0)
analytics-ruby (2.0.12)
appium_console (1.0.4)
appium_lib (8.0.2)
arel (6.0.3)
asset_sync (1.1.0)
ast (2.2.0)
attr_required (1.0.0)
authlogic (2.1.6)
autoparse (0.3.3)
autoprefixer-rails (6.3.1)
awesome_nested_set (3.0.2)
awesome_print (1.6.1)
aws-s3 (0.6.3)
aws-sdk (2.0.6.pre)
aws-sdk-core (2.0.6)
aws-sdk-resources (2.0.6.pre)
aws-sdk-v1 (1.65.0)
babel-source (5.6.16)
babel-transpiler (0.7.0)
babosa (1.0.2)
balanced (1.2.1)
bcrypt (3.1.10)
better_errors (1.1.0)
bigdecimal (1.2.4)
binding_of_caller (0.7.2)
blankslate (2.1.2.4)
bond (0.5.1)
bootstrap-sass (3.3.6)
browser (0.8.0)
builder (3.2.2, 3.0.4)
bundler (1.13.0.rc.1)
byebug (8.2.2)
camertron-eprun (1.1.0)
cancan (1.6.10)
cancancan (1.12.0, 1.10.1)
canonical-rails (0.0.11)
cap-recipes (0.3.39)
capistrano (2.15.5)
capistrano-maintenance (0.0.4)
capybara (2.4.4, 2.0.3)
carmen (1.0.2)
carmen-rails (1.0.1)
carrierwave (0.10.0)
carrierwave_backgrounder (0.4.1)
celluloid (0.16.0)
cert (1.4.1)
certified (1.0.0)
CFPropertyList (2.3.1)
charlock_holmes (0.7.3)
childprocess (0.5.5)
chronic_duration (0.10.6)
chunky_png (1.3.4)
claide (1.0.0)
cldr-plurals-runtime-rb (1.0.0)
climate_control (0.0.3)
cliver (0.3.2)
cocaine (0.5.7)
cocoapods (1.0.1)
cocoapods-core (1.0.1)
cocoapods-deintegrate (1.0.0)
cocoapods-downloader (1.0.0)
cocoapods-keys (1.4.0)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.0.0)
cocoapods-try (1.0.0)
coderay (1.1.0)
coffee-rails (4.1.1)
coffee-script (2.4.1)
coffee-script-source (1.10.0)
colored (1.2)
colorize (0.7.5)
columnize (0.9.0)
commander (4.3.5)
commonjs (0.2.7)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
concurrent-ruby (1.0.0)
connection_pool (2.2.0)
cork (0.1.0)
countries (0.11.5)
crack (0.4.2)
credentials_manager (0.16.0)
css_parser (1.3.6)
cupertino (1.3.4)
currencies (0.4.2)
daemons (1.2.3)
dalli (2.7.4)
database_cleaner (1.4.1)
debug_inspector (0.0.2)
debugger-linecache (1.2.0)
deface (1.0.1)
deliver (1.13.1)
devise (3.5.1)
devise-encryptable (0.1.2)
diff-lcs (1.2.5)
domain_name (0.5.24)
dotenv (2.0.2)
dotenv-deployment (0.0.2)
dynamic_form (1.1.4)
elasticsearch (1.0.12)
elasticsearch-api (1.0.12)
elasticsearch-model (0.1.7)
elasticsearch-rails (0.1.8)
elasticsearch-transport (1.0.12)
em-websocket (0.5.1)
erubis (2.7.0)
escape (0.0.4)
ethon (0.8.1)
eventmachine (1.0.4)
excon (0.45.4)
execjs (2.6.0)
extlib (0.9.16)
factory_girl (4.5.0)
factory_girl_rails (4.6.0)
faker (1.4.3)
faraday (0.9.1, 0.8.10)
faraday-cookie_jar (0.0.6)
faraday_middleware (0.10.0)
fastimage (1.6.8)
fastlane (1.97.2)
fastlane_core (0.48.1)
fb_graph2 (0.7.2)
ffaker (1.32.1)
ffi (1.9.10)
fission (0.5.0)
flaky (0.1.3)
fog (1.25.0)
fog-brightbox (0.7.2)
fog-core (1.32.0)
fog-json (1.0.2)
fog-profitbricks (0.0.3)
fog-radosgw (0.0.4)
fog-sakuracloud (1.0.1)
fog-softlayer (0.4.7)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-xml (0.1.2)
font-awesome-rails (4.5.0.0)
foreman (0.78.0)
formatador (0.2.5)
fourflusher (0.3.0)
frameit (2.7.0)
friendly_id (5.1.0)
fui (0.3.0)
fuubar (2.0.0)
fuzzy_match (2.0.4)
geocoder (1.2.9)
gh_inspector (1.0.2)
git-version-bump (0.15.1)
github-markup (1.1.2)
gitlab-grit (2.6.7)
gli (2.13.2)
globalid (0.3.6)
gmaps4rails (2.1.2)
gollum-lib (3.0.0)
google-api-client (0.9.11)
google_drive (0.3.9)
googleauth (0.5.1)
guard (2.12.8, 1.8.2)
guard-compat (1.2.1)
guard-livereload (1.4.0)
guard-rspec (4.6.0, 1.2.1)
guard-spork (1.5.2)
gym (1.6.3)
gyoku (1.1.1)
haml (4.0.6)
handlebars_assets (0.20.2)
hashie (3.4.2, 2.0.5)
heroku-deflater (0.5.3)
heroku_rails_deflate (1.0.3)
highline (1.7.3, 1.6.21)
hike (1.2.3)
hirefireapp (0.2.0)
hitimes (1.2.2)
hodel_3000_compliant_logger (0.1.1)
honeybadger (1.14.0)
hooks (0.4.1)
houston (2.2.3)
htmlentities (4.3.3)
http-cookie (1.0.2)
http_parser.rb (0.6.0)
http_router (0.11.1)
httparty (0.13.5)
httpclient (2.8.0)
httpi (2.1.1)
hurley (0.2)
i18n (0.7.0, 0.6.11, 0.6.9)
i18n_data (0.7.0)
imagga (1.0.0)
inflecto (0.0.2)
intercom-rails (0.2.29)
io-console (0.4.2)
ipaddress (0.8.0)
jbuilder (2.4.0)
jmespath (1.0.2)
journey (1.0.4)
jquery-fileupload-rails (0.4.6)
jquery-rails (4.1.0)
jquery-ui-rails (5.0.5)
json (1.8.3, 1.8.1)
jwt (1.5.1)
kaminari (0.16.3)
kgio (2.9.3)
koala (1.10.1)
kramdown (1.7.0)
krausefx-shenzhen (0.14.9)
launchy (2.4.3)
less (2.6.0)
less-rails (2.7.1)
libv8 (3.16.14.13)
listen (2.10.1)
little-plugger (1.1.4)
logging (2.0.0)
loofah (2.0.3)
lumberjack (1.0.9)
magnifier-rails (0.0.3)
mail (2.6.3, 2.5.4)
masonry-rails (0.2.4)
match (0.6.1)
mechanize (2.5.1)
memoist (0.12.0)
metaclass (0.0.4)
method_source (0.8.2)
middleman (3.3.12)
middleman-autoprefixer (2.4.4)
middleman-core (3.3.12)
middleman-gh-pages (0.0.3)
middleman-sprockets (3.4.2)
middleman-syntax (2.0.0)
mime-types (2.99, 1.25.1)
mini_magick (4.5.1)
mini_portile (0.6.2)
mini_portile2 (2.0.0)
minitest (5.8.4, 4.7.5)
mocha (1.1.0)
molinillo (0.4.5)
moneta (0.7.20)
monetize (1.1.0)
money (6.5.1)
mono_logger (1.1.0)
multi_json (1.11.2)
multi_xml (0.5.5)
multipart-post (2.0.0, 1.2.0)
mustache (0.99.8)
nap (1.0.0)
nenv (0.2.0)
net-http-digest_auth (1.4)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (2.9.2)
net-ssh-gateway (1.2.0)
netrc (0.10.3, 0.7.8)
newrelic_rpm (3.12.1.298)
nokogiri (1.6.7.2)
nori (2.3.0)
notiffany (0.0.6)
ntlm-http (0.1.1)
numerizer (0.1.1)
oauth (0.4.7)
oauth2 (1.0.0)
offsite_payments (2.0.1)
oink (0.10.1)
oj (2.12.10)
omniauth (1.2.2)
omniauth-facebook (2.0.1)
omniauth-oauth2 (1.3.1)
open4 (1.3.4)
opennebula (4.12.1)
orm_adapter (0.5.0)
os (0.9.6)
osx_keychain (1.0.1)
padrino (0.12.2)
padrino-admin (0.12.4, 0.12.2)
padrino-cache (0.12.4, 0.12.2)
padrino-core (0.12.4, 0.12.2)
padrino-gen (0.12.4, 0.12.2)
padrino-helpers (0.12.5, 0.12.4, 0.12.2)
padrino-mailer (0.12.4, 0.12.2)
padrino-support (0.12.5, 0.12.4, 0.12.2)
paperclip (4.2.1)
paranoia (2.1.0)
parser (2.3.0.3)
parslet (1.5.0)
pbxplorer (1.0.0)
pem (1.3.1)
pg (0.18.2)
phantomjs (1.9.8.0)
phony (2.14.8)
phony_rails (0.12.11)
pilot (1.9.2)
plist (3.1.0)
poltergeist (1.5.1)
polyamorous (1.1.0)
polyglot (0.3.5)
posix-spawn (0.3.9)
powerpack (0.1.1)
premailer (1.8.4)
premailer-rails (1.9.0)
produce (1.1.2)
protected_attributes (1.0.8)
pry (0.10.1)
psych (2.0.5)
puma (2.12.1)
pygments.rb (0.6.2)
rabl (0.11.4, 0.9.4.pre1)
rack (1.6.4, 1.5.2)
rack-cache (1.2)
rack-cachely (0.4.1)
rack-contrib (1.3.0)
rack-oauth2 (1.2.0)
rack-protection (1.5.3)
rack-rewrite (1.5.1)
rack-ssl (1.4.1)
rack-ssl-enforcer (0.2.8)
rack-test (0.6.3)
rack-timeout (0.2.4)
rails (4.2.5.1)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.7)
rails-html-sanitizer (1.0.3)
rails-i18n (4.0.8)
rails-observers (0.1.2)
rails4_upgrade (0.5.0)
rails_12factor (0.0.3)
rails_serve_static_assets (0.0.5)
rails_stdout_logging (0.0.4)
railties (4.2.5.1)
rainbow (2.1.0)
raindrops (0.13.0)
rake (10.5.0, 10.4.2, 10.1.0)
ransack (1.4.1)
rash (0.4.0)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
rb-kqueue (0.2.3)
rb-readline (0.5.3)
rbvmomi (1.8.2)
rd_awesome_nested_set (1.4.4)
rd_resource_controller (1.0.1)
rd_searchlogic (3.0.1)
rd_unobtrusive_date_picker (0.1.0)
rdoc (4.2.1, 4.1.0)
react-rails (1.6.0)
react_on_rails (2.3.0)
redcarpet (3.3.1)
redis (3.2.1)
redis-namespace (1.5.2)
ref (2.0.0)
remotipart (1.2.1)
representable (2.3.0)
responders (2.1.0)
resque (1.25.2, 1.24.1)
resque-rollbar (0.3.0)
resque-scheduler (2.2.0)
resque-web (0.0.6)
resque_mailer (2.2.7)
resque_spec (0.16.0)
rest-client (1.8.0)
retriable (2.1.0)
rmagick (2.15.3)
rollbar (1.5.3)
rouge (1.9.0, 1.3.4)
rspec (3.2.0, 2.14.1)
rspec-collection_matchers (1.1.2)
rspec-core (3.4.2, 3.2.2, 2.14.8)
rspec-expectations (3.4.0, 3.2.0, 2.14.5)
rspec-instafail (0.2.5)
rspec-mocks (3.4.1, 3.2.1, 2.14.6)
rspec-rails (3.4.2, 2.14.2)
rspec-support (3.4.1, 3.2.2)
rubocop (0.37.0)
ruby-hmac (0.4.0)
ruby-lint (2.1.0)
ruby-progressbar (1.7.5)
RubyInline (3.12.4)
rubyntlm (0.3.4)
rubyzip (1.1.7)
rufus-scheduler (2.0.24)
s3_direct_upload (0.1.7)
safe_yaml (1.0.4)
sanitize (2.1.0)
sanitize_email (1.1.5)
sass (3.4.21)
sass-rails (5.0.4)
savon (2.3.3)
scan (0.8.0)
screengrab (0.3.2)
scss_lint (0.44.0)
sdoc (0.4.1)
security (0.1.3)
select2-rails (4.0.1, 3.5.9.1)
selenium-webdriver (2.52.0)
send_with_us (1.10.2)
sendwithus_ruby_action_mailer (0.1.2)
sentry-raven (0.15.2)
sequel (4.11.0)
sheet_mapper (0.3.0)
shellany (0.0.1)
shenzhen (0.14.2)
sigh (1.8.0)
signet (0.7.3)
sinatra (1.4.6)
sitemap_generator (5.1.0)
slack-notifier (1.4.0)
slim (2.0.2)
slop (3.6.0)
snapshot (1.12.3)
spaceship (0.28.0)
spec (5.3.4)
spork (0.9.2)
spree (3.0.0)
spree_api (3.0.0)
spree_auth (0.30.1)
spree_backend (3.0.0)
spree_cmd (3.0.0)
spree_core (3.0.0, 0.30.1)
spree_dash (0.30.1)
spree_frontend (3.0.0)
spree_promo (0.30.1)
spree_sample (3.0.0)
spring (1.6.3)
spring-commands-rspec (1.0.4)
sprockets (3.5.2, 2.12.3)
sprockets-helpers (1.1.0)
sprockets-image_compressor (0.3.0)
sprockets-rails (3.0.1)
sprockets-sass (1.3.1)
sprockets_better_errors (0.0.4)
sqlite3 (1.3.11)
state_machine (1.2.0)
state_machines (0.2.2)
state_machines-activemodel (0.1.2)
state_machines-activerecord (0.2.0)
stathat (0.1.7)
stringex (2.5.2, 1.5.1)
supply (0.7.0)
switch_user (1.1.0)
temple (0.6.7)
term-ansicolor (1.0.7)
terminal-notifier (1.6.3)
terminal-table (1.4.5)
test-unit (2.1.2.0)
therubyracer (0.12.2)
thin (1.6.3)
thor (0.19.1, 0.18.1)
thread_safe (0.3.5)
tilt (2.0.2, 1.4.1)
time-helper (2.0.1)
timers (4.0.1)
toml (0.1.2)
tomlrb (1.2.0)
treetop (1.4.15)
trollop (2.1.2)
truncate_html (0.9.2)
turbolinks (2.5.3)
twitter-bootstrap-rails (3.2.2)
twitter_cldr (3.1.2)
typhoeus (0.8.0)
tzinfo (1.2.2, 1.2.1)
uber (0.0.15)
uglifier (2.7.2)
unf (0.1.4)
unf_ext (0.0.7.1)
unicode-display_width (0.3.1)
unicode_utils (1.4.0)
unicorn (4.8.3)
url_mount (0.2.1)
url_safe_base64 (0.2.2)
uuidtools (2.1.5)
validates_existence (0.9.2)
vegas (0.1.11)
versioncake (2.3.1)
warden (1.2.3)
wasabi (3.2.3)
web-console (2.3.0)
webmock (1.21.0)
webrobots (0.1.1)
websocket (1.2.1)
websocket-driver (0.6.2)
websocket-extensions (0.1.2)
wicked (1.1.1)
wicked_pdf (0.11.0)
will_paginate (3.0.7)
wkhtmltopdf-binary (0.9.9.3)
wkhtmltopdf-heroku (1.0.0)
word_wrap (1.0.0)
xcake (0.6.25)
xcode-install (1.4.0)
xcodeproj (1.1.0)
xcpretty (0.2.1)
xcpretty-travis-formatter (0.0.4)
xml-simple (1.1.4)
xpath (2.0.0, 1.0.0)
yajl-ruby (1.2.1)
ZenTest (4.11.0)

Error:
```
win@winmac ~/Development/iOS/Vango-iOS (develop)$ xcake make
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cork-0.1.0/lib/cork/board.rb:333:in `wrap_string': undefined method `winsize' for #<IO:<STDOUT>> (NoMethodError)
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cork-0.1.0/lib/cork/board.rb:80:in `puts_indented'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcake-0.6.25/lib/xcake/ui.rb:17:in `block in register_ui_hooks'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks.rb:51:in `run_hook'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcake-0.6.25/lib/xcake/command/make.rb:14:in `run'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
	from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcake-0.6.25/bin/xcake:7:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.2/bin/xcake:23:in `load'
	from /usr/local/var/rbenv/versions/2.1.2/bin/xcake:23:in `<main>'
```

Please let me know if you need any more information.

Thanks again!

**Comment by jcampbell05** [comment]
Interesting this seems to be an issue with the https://github.com/CocoaPods/Cork framework Xcake uses to output to the console.

@orta do you know anything about this error?

**Comment by sfkaos** [comment]
@jcampbell05 If it helps I found this. Which looks related. https://github.com/pry/pry/commit/f7c06f7e68b433293304dac30f786c6e92e00542

**Comment by orta** [comment]
Somehow you're using something that requires win size, before `require 'io/console'` [is called](http://ruby-doc.org/core-2.3.1/IO.html#class-IO-label-io-2Fconsole), would love to know how/why

**Comment by jcampbell05** [comment]
@orta The code for printing out the feedback is contained in this file
https://github.com/jcampbell05/xcake/blob/master/lib/xcake/ui.rb

We just create the `Cork::Board` instance and use all the various instance methods (i.e `notice`) like so when ever an event happens such as the project being created.

This is interesting though as on my machine I don't get this issue, so could it be environment related ?

**Comment by bluelucifer** [comment]
@jcampbell05 it causes from cork gem 0.1.0
in this command can't help on this problem. "gem install cork"
do not install from "gem install" command
I solve this problem from this command
git clone https://github.com/CocoaPods/Cork.git
cd Cork/
gem build cork.gemspec
gem install cork-0.1.0.gem

cork fix this bug but not updated yet.

**Comment by jcampbell05** [comment]
Okay I will close as an issue with Cork.

**Comment by jcampbell05** [comment]
@sfkaos A new version of the library causing this issue should be released if you `bundle update`
