### ISSUE TITLE
Different Build Configurations in the schema

### ISSUE THREAD

**Issue by irpainel** [jcampbell05/xcake#102]
Hi all, 

I'm trying to migrate my existing project to xcake and I'm facing a problem in the configurations.
In my existing project the schema has different build configuration for each phase, like this:
![screenshot_7_27_16__5_28_pm](https://cloud.githubusercontent.com/assets/2839084/17191437/47c2913a-5420-11e6-9bd6-e5a1531ad44c.png)

I want to achieve this in xcake but I can't figure out how to do it. In xcake the result is this one: 
![image](https://cloud.githubusercontent.com/assets/2839084/17191463/67549692-5420-11e6-866e-2bd44877d305.png)

My cakefile:
```
debug_configuration :Debug
release_configuration :Staging
release_configuration :Production

application_for :ios, 8.4 do |target|
  target.name = project.name 
  target.all_configurations.each do |c|
    c.settings["BUNDLE_ID"] = settings.fetch_app_identifier(c.name)
    c.settings["APP_NAME"] = project.name
    # fetches the project's shared configs
    project_settings.fetch("shared_config").each do |key, value|
      c.settings[key] = value
    end
    # fetches the configuration specific configs
    project_settings.fetch(c.name).each do |key, value|
      c.settings[key] = value
    end
  end
  unit_tests_for target
end
```

Thanks guys this is an awesome project, I'm trying to bring it to the company I work, it will be a lifesaver!

**Comment by maximkhatskevich** [comment]
@irpainel looks like Xcake does not support that currently. I would recommend to use one scheme for one purpose (with same build configuration for all phases). One for Debug. One for Adhoc staging builds, one for AppStore, etc. Especially with Xcake, when you do not need to manage it all manually. That brings more clarity for developers (you can quickly see which scheme is currently selected), than go inside scheme settings and check which phase connected with which configuration, especially when several developers are working on the same project.

**Comment by irpainel** [comment]
@maximkhatskevich! that makes sense, i'm going to try to do that. Thanks for the reply :D

**Comment by jcampbell05** [comment]
Thanks for replying @maximkhatskevich! Lets us know if you need anything else @irpainel
