### ISSUE TITLE
Create "Folder references" instead of "Groups" to organize source files

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#106]
At least optionally. At least for files that we add into the project with "Include files" command explicitly. My use case is that I keep everything synchronized in Finder and Xcode anyway, so if I regenerate project - it will recreate the needed project structure again. Creating "groups" instead of Folder references does not make sense - just creates extra work for developers.

**Comment by jcampbell05** [comment]
@maximkhatskevich I could look into exposing a property on the project what do you think ? 
`project.added_folders_type = :folder_reference`

**Comment by maximkhatskevich** [comment]
@jcampbell05 yes, something like this is exactly what I would need.
Maybe something like

```Ruby
project.add_folders_as = :reference # alternative/default value is ":groups"
```

**Comment by maximkhatskevich** [comment]
@jcampbell05 probably this is not needed, for now, because it produces a strange issue in Xcode 7.3.* http://stackoverflow.com/a/36429157
