### ISSUE TITLE
Support paths outside of the project root dir

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#107]
Something like...

``` Ruby
target.include_files << "./../MyApp-Common/Src/*.*"
```

... is not supported now, but is useful when you share some code between different projects (like iOS and server side, etc.).

**Comment by jcampbell05** [comment]
@maximkhatskevich good point, will have to check out how Xcode handles this. Keep the feature requests coming though. lots for 0.7 :)

**Comment by jcampbell05** [comment]
@maximkhatskevich  do you know how Xcode handles this ?

**Comment by maximkhatskevich** [comment]
@jcampbell05 based on my experience, Xcode handles this very well, no problem. I can add manually files from any location outside project root directory, and I can put it anywhere inside logical groups hierarchy. It supports adding individual files as well as entire folders and associate groups with it. Does it answer your question?

**Comment by jcampbell05** [comment]
@maximkhatskevich  do you still need this ? :)

**Comment by maximkhatskevich** [comment]
Didn't use that functionality for a long time. May be useful in future, but not a high priority for sure. Feel free to ignore for now.
