### ISSUE TITLE
undefined method `ui_tests_for'

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#109]
Tried to regenrate project using Cakefile from https://github.com/jcampbell05/xcake/issues/108 and got this error. Any ideas?

**Comment by maximkhatskevich** [comment]
Just updated to latest Xcake available via "gem install".

**Comment by jcampbell05** [comment]
@maximkhatskevich I need to publish `master` to RubyGems as it has the new `ui_tests_for`

**Comment by maximkhatskevich** [comment]
@jcampbell05 okay, no rush for now, just wanted to make sure this is something we know about. Please, let me know when it's published.
