### ISSUE TITLE
Sample Cakefile iOS framework target

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#110]
I can provide sample/template Cakefile for iOS framework target, which contain all the settings Xcode sets by default to that kind of target when you create one manually from Xcode. What do you think @jcampbell05 ?

**Comment by jcampbell05** [comment]
@maximkhatskevich  sure go for it :)

**Comment by amotion** [comment]
@maximkhatskevich would love to see an example of how to include a framework target as a linked framework/library in the application_for target. Is that part of your sample template?

**Comment by maximkhatskevich** [comment]
@amotion sure, take a look at this line: https://github.com/jcampbell05/xcake/blob/master/docs/Sample/Cakefile#L298
So far it worked well for me.

**Comment by amotion** [comment]
@maximkhatskevich Ah ok, for me that ends up pointing to a framework in the SDK folder, but my framework is defined as a target in my project:

<img width="158" alt="screenshot 2016-09-06 19 19 16" src="https://cloud.githubusercontent.com/assets/79704/18294398/d83d7494-7466-11e6-86e5-bf7159f40176.png">

I'm trying to get UniverseKit linked here:

<img width="575" alt="screenshot 2016-09-06 19 20 00" src="https://cloud.githubusercontent.com/assets/79704/18294405/ecd550b6-7466-11e6-9d87-ac9f3ca752fa.png">

**Comment by maximkhatskevich** [comment]
@amotion oops, sorry. Yes, my example is about system/Apple frameworks. I never tried to include frameworks manually this way, so I'm not using Xcake for this.

Depending on the purpose of having that custom framework next to application target, I would recommend you to use one of the alternative ways listed below (you decide which one suites better for your needs).

1) Share files. Create a folder like "Common" and put there source files that you can include in different application targets.
2) Via CocoaPods. Make your framework a separate project and put it in a separate folder, then add there Podspec file. After this, you can add this framework to your main project as a regular pod - just point to a local path (like `pod 'UniversalKit', :path => '../UniversalKit'`) or put your framework on GitHub as private or public repo and put URL to it explicitly in your Podfile (like `pod 'UniversalKit', :git => 'https://github.com/amotion/UniversalKit.git'`).

@amotion I hope it makes sense for you. Lmk if you have any questions.
