### ISSUE TITLE
Adding a Messages Extension

### ISSUE THREAD

**Issue by amotion** [jcampbell05/xcake#112]
Is there any way to add an iMessage Extension via xcake?

<img width="766" alt="screenshot 2016-09-07 10 46 53" src="https://cloud.githubusercontent.com/assets/79704/18316399/6fe17e4a-74e8-11e6-8bb3-08bd9bf7f99e.png">

**Comment by amotion** [comment]
Figured it out! You have to set `target.type = :messages_extension`

**Comment by jcampbell05** [comment]
@amotion glad its sorted, I'll try and add this to the docs!
