### ISSUE TITLE
Ability to set development team (and ProvisioningStyle) in Xcode 8 via Cakefile

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#113]
It's a per-configuration target build setting in Xcode 8, but it's not being set as other build settings. Next to "DevelopmentTeam" setting, Xcode also sets "ProvisioningStyle" setting. See screenshot below:

<img width="481" alt="screen shot 2016-09-12 at 10 34 20 pm" src="https://cloud.githubusercontent.com/assets/2624646/18453867/1a433a00-7939-11e6-859d-f04c286c9b89.png">

**Comment by maximkhatskevich** [comment]
Looks like it might be done like this (for a macOS app target):

`Ruby
if configuration.name == "Debug"

    configuration.settings["CODE_SIGN_IDENTITY"] = "Mac Developer"
    configuration.settings["DEVELOPMENT_TEAM"] = "XXXX" # desired team id here

end
`

**Comment by jcampbell05** [comment]
@maximkhatskevich Cool so do you think we should have a document about the new xcode 8 signing settings ?

**Comment by maximkhatskevich** [comment]
Yes, a note about it is worth to be added in the Readme file, I think. I'm investigating now how it works.

Side note: when I generate project file using latest Xcake (0.7.1) and first time launch with Xcode 8, there is a button like "Enable automatic signing". If I hit this button - Xcode uses the settings I mentioned above, but entire Xcode file is being replaced with something that looks similar, but uses different format, something similar  to JSON, but not fully valid JSON (before it was XML, as you know). So my question is can we do something to generate project file in the right fromat out of the box or it's something outside Xcake power (we rely on some kind generator provided by Apple/3dparty)?

**Comment by jcampbell05** [comment]
@maximkhatskevich I'm thinking it may be ASCII Plist, I think someone is working on a library Xcake will use in the future to support this. 

For now you either have to convert the Xcode file afterwards using a tool (There is a tool for this but I forget which) or update Xcodeproj to a version built for Xcode 8 since this is the library that supports it.
