### ISSUE TITLE
NO need to set "TEST_HOST" and "BUNDLE_LOADER" build settings for UI tests target

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#115]
Currently the attempt to run tests with UI tests target generated by Xcake fails with error message like this:

"Invalid configuration: MyAppUITst sets both USES_XCTRUNNER and TEST_HOST"

After short investigation I found out that we should not set "TEST_HOST" and "BUNDLE_LOADER". After fixing https://github.com/jcampbell05/xcake/issues/108 everything should start working out of the box after generating project file from Cakefile.

**Comment by jcampbell05** [comment]
Is this new for Xcode 8?

**Comment by maximkhatskevich** [comment]
@jcampbell05 as I remember, it was happening in Xcode 7 too. The point is that UI tests are working a bit different than unit tests - the difference is described above.

**Comment by jcampbell05** [comment]
@maximkhatskevich  Cool will update this not to be set for UITests.

**Comment by jcampbell05** [comment]
@maximkhatskevich do you know which of these build settings we should remove ?

**Comment by maximkhatskevich** [comment]
@jcampbell05 my understanding is that we should not set both of these parameters.

**Comment by jcampbell05** [comment]
Cool I'm just trying to figure out which one needs being set for UITests and which one for Unit Tests :) to ensure we have it set correctly.

**Comment by maximkhatskevich** [comment]
I would create sample targets in an Xcode project and check there :) Don't want to give you wrong answers, didn't touch this for some time.

**Comment by jcampbell05** [comment]
@maximkhatskevich cool will do so :) 👍

**Comment by jcampbell05** [comment]
Looked at struct looks like we can remove TEST_HOST.
