### ISSUE TITLE
Add legacy swift version flag

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#117]
We should set this in Xcake.

**Comment by maximkhatskevich** [comment]
What's the difference from #116?

**Comment by jcampbell05** [comment]
@maximkhatskevich  One is the example of how to switch between swift 2 and 3. this is just to make sure Xcake sets the setting to a default value when generating the project so xcode doesn't complain.

**Comment by maximkhatskevich** [comment]
got it, so this one seems to be on you.

**Comment by jcampbell05** [comment]
Should be fixed by making sure latest Xcodeproj is installed as they should handle it, will close this when we've bumped it.
