### ISSUE TITLE
How to add custom scripts to Build Phases?

### ISSUE THREAD

**Issue by chiahsien** [jcampbell05/xcake#122]
First of all, thanks for your work, it's awesome!

I've searched the issues and read all the docs, but I can't find a way to add custom scripts to `Build Phases`.

For example, if I use Fabric's Crashlytics to collect crash reports, I need to add a script to Build Phases.

How can I do that?

**Comment by jcampbell05** [comment]
Yes that's possible 😀 reason it's probably not documented yet is we are still working on the API for it.

But for now you can see how to use it in this pull request

https://github.com/jcampbell05/xcake/pull/37

**Comment by chiahsien** [comment]
Thanks, it works!
