### ISSUE TITLE
How to customize schemes?

### ISSUE THREAD

**Issue by chiahsien** [jcampbell05/xcake#124]
I've read the [Xcode Project Support.md](https://github.com/jcampbell05/xcake/blob/master/docs/Xcode%20Project%20Support.md), and it says that I can't manual control the schemes.

What I need is to:

- Add pre-actions and/or post-actions into schemes.
- Add arguments and/or environment variables.

Is there any chance to add this feature? Or can I use any shell/ruby/python/whatever script to achieve it?

**Comment by jcampbell05** [comment]
@chiahsien Currently there isn't any way to customise it but I'm thinking of adding a hook to allow you to modify the resulting project file using `xcodeproj` so you can do things xcake doesn't let you yet.

**Comment by maximkhatskevich** [comment]
I never needed this by myself, but I agree it would be nice to have that feature in Xcake.

**Comment by jcampbell05** [comment]
In 0.8.2 we are allowing you to specify your own schemes due to popular demand. I'll have a little think on how to implement the pre and post actions.

**Comment by jcampbell05** [comment]
@lyptt any of these useful for Struct ? The ones for the environmental variables is useful especially for the flags for debugging CoreData

**Comment by lyptt** [comment]
@jcampbell05 I'm absolutely happy to consider scheme configuration as an optional addition to a spec file. If it turns out it's a feature users need, it's worth including. I also like the idea of build hooks via DSL e.g. prebuild/preparse/postparse/postbuild.

**Comment by jcampbell05** [comment]
@lyptt yeah hooks are interesting, I have one for postgeneration in xcake so you can trigger it :)

**Comment by jcampbell05** [comment]
Since we are winding down active development of Xcake I will instead look into getting this into Struct
