### ISSUE TITLE
Use different configuration for other targets

### ISSUE THREAD

**Issue by rock88** [jcampbell05/xcake#126]
Hi!
Can I use different build configurations for other targets?
For example,
I have two targets:

- app-stage
- app-appstore

and I want to use Debug only for app-stage and Release only for app-appstore, how I can do this?

**Comment by jcampbell05** [comment]
@rock88 Xcake should do this out of the box without the need for multiple targets. If you specify the build configurations for a target then xcake will generate a scheme for you.

However if  you still want to do it this way, specifying your own build configurations for the project will stop xcake generating the defaults (just provide a name for it as a parameter). 

I'm not sure if the Xcode project allows you to do this though.

**Comment by maximkhatskevich** [comment]
@rock88 Xcode defines build configurations per project, so all targets share the same set of configurations. That means for every target you'll be able to set the same build settings for all configurations, or different settings per each configuration. Xcake also will generate Schemes for each target and configuration. For example, if you have targets "t1" and "t2" and configurations "Debug", "Stage" and "AppStore", then you'll have 2*3 = 6 Schemes: "t1-Debug", "t1-Stage", "t1-AppStore", "t2-Debug", "t2-Stage", "t2-AppStore".

As a best practice, what you are trying to achieve (based on the names of targets you provided) is usually done by having different build configurations (as in my example above) for a single target. That's true if these versions of the app have the same source files included and the only difference between debug/stage and AppStore version of the app are build settings (note, that you can include any custom/user-defined build settings - for things like API server address, etc. - and have references to them from your Info file to access them in run time), as well as you can have different dependencies (for example, via Cocoapods) for different build configurations of the same target.

But even if you still need several targets - Xcake will generate all schemes for all targets, but it's up to you which ones to use for one target, and which ones to use for another target - I mean you can just ignore (or even hide) some schemes for some targets if you do not need them).

I hope that helps.

**Comment by rock88** [comment]
@jcampbell05 @maximkhatskevich  I think you are right, and few schemes for one target it's not problem.
Thanks you!
