### ISSUE TITLE
XCake generating corrupted .xcodeproj file

### ISSUE THREAD

**Issue by kirakik** [jcampbell05/xcake#128]
I'm attempting to create a simple XCake file:

``` ruby
  application_for :ios, 9.0 do |target|
      target.name = "Samsao" 
  end
```

After successfully running `xcake make`, the `.xcodeproj` file that was generated refuses to open. I', getting the following error: 
`xxxx.xcodeproj cannot be opened because the project file cannot be parsed`

Has anybody encountered this before? Any clue as to what could be going on?

**Comment by jcampbell05** [comment]
Hey, firstly could you tell me what version of Xcode, xcake and the xcodeproj gem you have. It could be that one of these are out of date and causing issues.

**Comment by maximkhatskevich** [comment]
@kirakik first of all, could you please provide full Cakefile? If your Cakefile contains only what you listed above then that might be not enough for a working basic project file. @jcampbell05 what do you think?

**Comment by jcampbell05** [comment]
@maximkhatskevich  Potentially. Ideally Xcake should try to help you out with providing enougth defaults that Xcode is happy. So we should definatly investigate this.

**Comment by kirakik** [comment]
> xcake: 0.7.1
> Xcode: 8.1
> xcodeproj: 1.4.1

I was initially trying to create more complex Cakefiles. but ended up with this as I kept getting that error and was trying to trim it off to get a basic version working. The initial Cakefile I had looked something like this:

``` ruby
  project.name = "Samsao"
  project.organization = "Samsao"

  application_for :ios, 9.0 do |target|
      target.name = "Samsao" 
      target.type = :application
      target.language = :swift
      target.platform = :ios
      target.include_files = ["App_Name/**/*.*"]

      unit_tests_for target
      ui_tests_for target
  end

Project.new do |c|
  after_save do
  `bundle install`
  `bundle exec pod install`
  end
end
```

**Comment by maximkhatskevich** [comment]
@kirakik try to start with our sample project and Cakefile included there: https://github.com/jcampbell05/xcake/tree/master/example/app/CakeMania

Just fetch entire repo, go into this folder and run "xcake make", then try to open the newly generated "CakeMania.xcodeproj" file with Xcode and see what happens. If it will work - then start experimenting from there. If you'll have any issues - let us know.

**Comment by maximkhatskevich** [comment]
@jcampbell05 I'm not sure about this part at all - should it work or should it just break everything:

`Project.new do |c|
  after_save do
  `bundle install`
  `bundle exec pod install`
  end
end`

**Comment by maximkhatskevich** [comment]
Also @kirakik I think you should not have these lines

```Ruby
unit_tests_for target
ui_tests_for target
```

if you do not provide any details inside each of these test targets (like info file and source files). @jcampbell05 correct me if I'm wrong.

Also I would not use Cakefile for running `bundle install` and `bundle exec pod install`. From my point of view, that kind of automation should be done outside of Xcake, with tools like Fastlane, on demand.

**Comment by chiahsien** [comment]
@kirakik 

- Use your text editor (Sublime Text, Atom, etc.) to open `YourProject.xcodeproj/project.pbxproj` file
- Around line 4, there should be something like `classes = ;`, change it to `classes = { };`
- Save

See if it works for you.

This should be `xcodeproj 1.4.1` bug? It works fine in `xcodeproj 1.3.3`.
cc @maximkhatskevich @jcampbell05

**Comment by jcampbell05** [comment]
@chiahsien Potentially I've spotted an issue regarding build settings so maybe it could be releated https://github.com/CocoaPods/Xcodeproj/issues/453

**Comment by jcampbell05** [comment]
@kirakik  @maximkhatskevich  The multiple projects are potentially confusing Xcake, if you remove the last block and see if that helps.

Xcake already has an implicit one for the file.

**Comment by kirakik** [comment]
The problem looks like it's indeed related to the `project.pbxproj` file, @chiahsien's suggestion solved it!

@maximkhatskevich @jcampbell05  The problem persists with the sample project and after removing the last block. It does look like it's related to my setup, as I tried it on another computer using xcodeproj 1.3.3, and everything worked fine there with the same Cakefile. I will be careful to remove those lines you mentioned, I was just experimenting with what I could do :)

**Comment by jcampbell05** [comment]
Cool, at least we've narrowed it down.. So it's potentially due to a more recent version of xcodeproj ?

**Comment by kirakik** [comment]
It looks like it to me

**Comment by maximkhatskevich** [comment]
I have "xcodeproj v.1.3.1" and have no issues like listed above, by the way, so yes @jcampbell05 I would agree with you.

**Comment by lucaquerella** [comment]
I had the same problem and I fixed by downgrading from `xcodeproj-1.4.1` to `xcodeproj-1.3.3`.

**Comment by jcampbell05** [comment]
@lucaquerella interesting, will have a look in what changes have occured to cause that.

**Comment by chiahsien** [comment]
Any progress about this issue?

**Comment by jcampbell05** [comment]
@chiahsien I'm rigging up a new testing matrix for our CI, I'm hoping that way I can test against the new xcodeproj and fix this.

**Comment by jcampbell05** [comment]
Closing this as I've tested 1.4.1 against 0.8.0 and it seems to be okay. But let me know if there are other issues
