### ISSUE TITLE
Target's extensions are not being set properly

### ISSUE THREAD

**Issue by kirakik** [jcampbell05/xcake#129]
**Setup:**
> xcake: 0.7.1
> Xcode: 8.1
> xcodeproj: 1.4.1

**Issue:**
After running `xcake make` and opening the `.xcodeproj` file, I find the following targets under the Products group:
```
AppName.
AppNameTests.
AppNameUITests.
```

In my experience, these should be:

```
AppName.app
AppNameTests.xctest
AppNameUITests.xctest
```

Any clue as to how to fix this issue?

**Comment by jcampbell05** [comment]
@kirakik  looks like a bug with `Xcake` I'll take a look but potentially you could override the target name ?

**Comment by kirakik** [comment]
@jcampbell05 I tried that, unfortunately adding a `.app` or `.xctest` to the target name leads to this:  `AppName.app.` or `AppName.xctest.`

**Comment by chiahsien** [comment]
It happens to me, too. What's interesting is that although the displayed extension is missing, the path it pointed to is correct.

**Comment by jcampbell05** [comment]
Interesting, if you could upload a project that reproduces this problem then I can take a look :) also if you could tell me your `xcodeproj` version

**Comment by chiahsien** [comment]
xcodeproj v1.3.3 & v1.4.1
There is no specific step and/or setting to reproduce this problem, it just happens.
https://github.com/jcampbell05/xcake/files/610458/XcakeTest.zip

**Comment by jcampbell05** [comment]
So had a look into this, it seems cosmetic. Xcode will use the correct extensions. 

I'm looking into how I can force it to show as the correct extension in the project, I'm figuring out where this behaviour happens within Xcodeproj.

**Comment by jcampbell05** [comment]
Seems quite hard to fix and it's more of a cosmetic issue.
