### ISSUE TITLE
Work with 3rd-party frameworks 

### ISSUE THREAD

**Issue by rock88** [jcampbell05/xcake#131]
Hi,
Can I add 3rd-party frameworks to Embed Frameworks build phase & Embedded Binaries target section?

**Comment by jcampbell05** [comment]
@rock88 Yes just add it to the list of files to be included and Xcake will add it for you

**Comment by rock88** [comment]
@jcampbell05 Thanks for answer!
I did it:

`target.include_files << "Carthage/Build/iOS/Alamofire.framework"`

But Alamofire.framework added only to `Link Binary with Libraries`, not to `Embed Frameworks`

**Comment by jcampbell05** [comment]
@rock88  Ah, sorry I mis understood. I guess I'll have to expose a way of adding it to that phase.

**Comment by jcampbell05** [comment]
We've exposed a new embed DSL in 0.8.8

**Comment by RikkiGibson** [comment]
How does the embed DSL work?

**Comment by RikkiGibson** [comment]
After some hunting, I found creating a block like this does the job.

```ruby
target.copy_files_build_phase "Embed Frameworks" do |phase|
    phase.files = ["Carthage/Build/iOS/PromiseKit.framework"]
    phase.destination = :frameworks
    phase.code_sign = true
end
```

Would it be alright for me to try and roll up my sleeves and document some of these features in a way that's somewhat easier to discover?

**Comment by jcampbell05** [comment]
Yes please
