### ISSUE TITLE
Method to disable Automatic Code Signing in Xcode 8

### ISSUE THREAD

**Issue by atreat** [jcampbell05/xcake#132]
I see in the [example CakeMania Cakefile](https://github.com/jcampbell05/xcake/blob/da11919ffaf15742b49582dc0ca61db30c8bb44c/example/app/CakeMania/Cakefile#L238-L240) there is way to enable automatic signing. I'm wondering, is there a way do set this to be manual?

I'm using fastlane's [match](https://github.com/fastlane/fastlane/tree/master/match) to to handle my teams code signing. It seems when I build the project on CI the default value for Automatic Code signing is set.

I know one of the major configurations to set this occurs in the project.pbxproj file. In the PBXProject object's `attributes` there is a section of `TargetAttributes`.
```
TargetAttributes = {
    9EE7CAE93A712E88371C9275 = {
        ProvisioningStyle = Manual;
    };
};
```
In the [CakeMania project.pbxproj](https://github.com/jcampbell05/xcake/blob/da11919ffaf15742b49582dc0ca61db30c8bb44c/example/app/CakeMania/CakeMania.xcodeproj/project.pbxproj#L234) this only includes the DevelopmentTeam.

Does xcake have any mechanism to set this? If not could you point be to the best section of code where I may try out some the changes and(hopefully) open a PR?

**Comment by jcampbell05** [comment]
So right now no. From what I've read the target attribute is a new thing and xcake's underlying library xcodeproj as far as I'm aware does t support it yet.

Maybe @orta or @neonacho can confirm this

**Comment by atreat** [comment]
@jcampbell05 yes after opening this issue I searched through xcodeproj's issue and found something similar [#384](https://github.com/CocoaPods/Xcodeproj/issues/384). It looks like xcodeproj doesn't have support to manage the projects `TargetAttributes` quite yet. 

There is the [update_project_codesigning](https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning/blob/master/lib/fastlane/plugin/update_project_codesigning/actions/update_project_codesigning_action.rb) fastlane plugin that should update the project configuration in a way that properly sets the Manual codesigning, but I haven't had any luck using it just after xcake creates my project.

I'll keep investigating to see what is possible, if I find something that works I'll open a PR for either xcake or for xcodeproj.

**Comment by jcampbell05** [comment]
I'll close this for now as it seems like we can't do anything about it.
