### ISSUE TITLE
0.8.11: Fix All The Things

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#145]
Seems a few niggly issues have crept in which we should fix in 0.8.10 before adding in any new features.

- [x]  #154
- [x] #143 
- [x] #144 
- [x] #129 
- [x] #115 
- [x] #114 
- [x] #108 
- [x] #156

**Comment by maximkhatskevich** [comment]
Agree, fixing bugs is always way more important than new features!

**Comment by jcampbell05** [comment]
So 4 more issues left to fix :)

**Comment by jcampbell05** [comment]
Releasing 0.8.9 today so users can benefit from the fixes and then will release a second wave of fixes in 0.8.10

**Comment by jcampbell05** [comment]
Xcake 0.8.9 should now be released :)

**Comment by RikkiGibson** [comment]
Would any of these be suitable for some guy to show up and try to solve?

**Comment by jcampbell05** [comment]
@RikkiGibson  all the remaining things should be easy to fix :) just small tweaks.

**Comment by jcampbell05** [comment]
2 left now ! :)

**Comment by dirkoswanepoel** [comment]
Would it be possible to publish a new gem? The current one does not include fixes #178 and #179

**Comment by jcampbell05** [comment]
@dirkoswanepoel sure :)

**Comment by albertoschiariti** [comment]
Hi James. Still didn't see the update... It's over 2 weeks. I know that you're not being payed for this, but you told me 2 weeks ago that you would update the gem. Just let me know if you're busy and I will search another solution, no problem :-)

**Comment by jcampbell05** [comment]
@albertoschiariti should be up now :) sorry for the delay :)

**Comment by albyok** [comment]
Thanks dude :-)
