### ISSUE TITLE
New description for the repo

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#146]
I would suggest to slightly improve the repo description, this is how I think would be better:

"Describe Xcode project in a human readable format and (re)generate one on demand."

**Comment by jcampbell05** [comment]
@maximkhatskevich we should probably look at the new Struct tool released the other day and see what we can improve on https://www.get-struct.tools/ 

We should think about gaining a website even if it's just a github page.

**Comment by maximkhatskevich** [comment]
Wow! Didn't know you are working on something new :) Will take a look on it.

**Comment by maximkhatskevich** [comment]
@jcampbell05 so this is not your tool, this is a similar tool from another developer, right? Don't you think to discuss with him to merge both of your projects or deprecate one of them and work together on a single project, since you are doing the same job?

**Comment by jcampbell05** [comment]
Yeah that is another tool not mine. Good point I'll reach out to him 😀

**Comment by maximkhatskevich** [comment]
Great! I checked his tool. He has slightly different approach, but definitely functionality of the tool is very similar to Xcake, so everyone would benefit from collaboration, I think. Please keep me posted on that.

**Comment by jcampbell05** [comment]
@maximkhatskevich so you can follow our discussion here:
https://github.com/lyptt/struct/issues/22

**Comment by jcampbell05** [comment]
@maximkhatskevich so, it seems so far that Struct fits a very different role to Xcake in ethos. But lets see :) 

It seems most of the functionality is there that we have in Xcake plus he already has features we were planning to add such as JSON, YAML and Recreation of project. The traction from his website is also amazing, so obviously it's been nailed :)

**Comment by maximkhatskevich** [comment]
Thanks for the link, I'm subscribed there now. So far I definitely like/understand/prefer Xcake much more and will continue using it. I'll keep watching on your conversation and we will see where it will lead us.

**Comment by maximkhatskevich** [comment]
In the mean time, what about to update the repo description? Do you agree or not with it? :) either way is fine for me, lets just make decision and close this issue - whatever you decide to apply new description or reject it.

**Comment by jcampbell05** [comment]
:) no sounds perfect, I'll update it for the 0.8.9 release :) I'm going to open some issues regarding some of the struct stuff, as I've noticed somethings xcake could be doing

**Comment by maximkhatskevich** [comment]
Ok.

**Comment by jcampbell05** [comment]
Updated :)

**Comment by maximkhatskevich** [comment]
Great. I see you updated description in Readme, but forgot to update description of the repo on GitHub (in the top of the GitHub page).

**Comment by jcampbell05** [comment]
Good catch updated :)
