### ISSUE TITLE
Adding files into "Compile sources" Build Phase sorted by name alphabetically

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#148]
@jcampbell05 it would be super handy if Xcake were adding files into "Compile sources" Build Phase sorted by name alphabetically. This would solve the compilation issue that happens when you have an extension of a nested Swift type outside of the file where this type was originally declared.

How hard it is to add this feature into Xcake by default or make it an option in Cakefile? For now I'm just rearrange files manually after I regenerate project file with Xcake to workaround this compilation issue in Xcode.

**Comment by jcampbell05** [comment]
@maximkhatskevich Yeah, that makes sense :) I'll implement that, in theory should be easy but I'll look at what that needs.

**Comment by jcampbell05** [comment]
Will put this in 0.8.10

**Comment by jcampbell05** [comment]
@maximkhatskevich  btw in the meantime one trick you can do is manually re-specifiy the files that need to be built in order like so:

```
target.include_files = ["**/*.*"] # dont care about the order
target,include_files << "source/me_first.c" # is placed before "me_second"
target,include_files << "source/me_second.c" # is placed after "me_first"
```

**Comment by maximkhatskevich** [comment]
Okay, got it.

**Comment by jcampbell05** [comment]
@maximkhatskevich if this workaround worked for you then I would suggest moving over to Struct eventually as it's built to already do this.

**Comment by maximkhatskevich** [comment]
Agree!
