### ISSUE TITLE
xctool is deprecated - are we aware about it?

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#149]
@jcampbell05 I remember you mentioned few times 'xctool' when we were discussing issues with Xcake. I heard this word but never paid attention to that, never discovered what it is. Today I've checked what it is and find out that this is a 3d party tool made by Facebook, and it is now deprecated https://github.com/facebook/xctool/issues/704#issuecomment-234237405 Do we know that? Do you still use it for Xcode 8? maybe this is why we have so many issues with Xcake recently?? Because we are using deprecated tool with Xcode 8 while this tool is not supposed to work properly with Xcode 8?

**Comment by jcampbell05** [comment]
So I've used `xctool` to work around Xcodeproj not creating Xcode Projects in ASCII format. They have since fixed this problem by changing the way they generate the projects.

Xctool was always used in my scripts but never as part of Xcake :) so we should be fine.

**Comment by maximkhatskevich** [comment]
Okay, thanks for clarification!
