### ISSUE TITLE
Project Watcher

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#150]
Struct has a cool watcher that will regenerate a project when ever it detects changes or files being added to the project directory.

We should probably do this too

**Comment by maximkhatskevich** [comment]
To be honest, I see no value in it! I would prefer to be fully in control of when my project is being regenerated and not polluting my commit with unexpected project regeneration. Plus, Xcake has many small issues or does not provide everything I need, so after regenerating project I usually need to do few adjustments manually before continue working normally. I understand this is an optional feature, but I find it completely unnecessary and just wast of time, you better focus on known issues and more needed features. Plus, when you add file, you usually do it from Xcode, add to a group, and based on the group, Xcode suggests you proper default physical location in file system. Once file created - you have it added under the group where you started "Add new file" process, so there is absolutely no need to regenerate entire project. IMHO, of course.

**Comment by jcampbell05** [comment]
Thats true and I would imagine most people who use watchers may have their own dedicated thing for triggering it. Also I tend to just manually run `xcake make` after every change. 

So we should probably ignore this for now.

**Comment by maximkhatskevich** [comment]
Agree :)
