### ISSUE TITLE
JSON + Yaml Format

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#151]
Struct has support for JSON and Yaml, we should probably add it too

**Comment by maximkhatskevich** [comment]
I would love to see it in JSON, but any format is okay. IMHO it does not matter which format the spec is uses. the more important is what the tool allows you to do, how stable and reliable it is. Learning new spec format is not a big deal for newcomers, whatever it is - YAML, JSON or Ruby. Again, I think we should focus on know issues and most wanted features than on convenience extensions. I think it's, at least, unnecessary at current point to spend manpower on this feature. Also I do not see much value supporting multiple formats, that does not bring any functional value.

**Comment by jcampbell05** [comment]
I guess as long as the Ruby format stays easy enough to understand :) If people decide they need it then we can do it.

**Comment by maximkhatskevich** [comment]
Fair enough!
