### ISSUE TITLE
Crashes again

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#154]
Setting up a new iOS framework repo. Tried to use Xcake from within Fastlane lane, got a crash. The Cakefile is 100% valid, just copied from another framework where it has no issues, changed the name of the project and added couple more build settings.

Here is the log:

fastlane finished with errors

[!] Exit status of command 'cd ./.. && xcake make && pod update --no-repo-update' was 1 instead of 0.
/Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/generator/scheme_generator.rb:33:in `block in visit_target': undefined method `build_for_running' for #<Xcodeproj::XCScheme::BuildAction:0x007fd16b2ea4e8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/generator/scheme_generator.rb:16:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/generator/scheme_generator.rb:16:in `visit_target'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/visitor.rb:45:in `visit'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:83:in `block in accept'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/dsl/project.rb:82:in `accept'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:25:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/lib/xcake/command/make.rb:23:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/xcake-0.8.8/bin/xcake:6:in `<top (required)>'
	from /usr/local/bin/xcake:23:in `load'
	from /usr/local/bin/xcake:23:in `<main>'
  - Reading Cakefile
  - Creating Project
  - Creating Target<MKHXCTRequirementTst>
  - Creating Target<MKHXCTRequirement>
  - Resolving Project
  - Resolving Target<MKHXCTRequirementTst>
  - Resolving Target<MKHXCTRequirement>
  - Creating build configurations for Project<MKHXCTRequirement>
  - Creating build configuration Debug for Project<MKHXCTRequirement>
  - Creating build configuration Release for Project<MKHXCTRequirement>
  - Creating build configurations for Target<MKHXCTRequirementTst>
  - Creating build configuration Debug for Target<MKHXCTRequirementTst>
  - Creating build configuration Release for Target<MKHXCTRequirementTst>
  - Creating build configurations for Target<MKHXCTRequirement>
  - Creating build configuration Debug for Target<MKHXCTRequirement>
  - Creating build configuration Release for Target<MKHXCTRequirement>
  - Creating User Schemes

**Comment by maximkhatskevich** [comment]
Any ideas what to do?

**Comment by jcampbell05** [comment]
@maximkhatskevich could you tell me what version of `xcodeproj` you have ? I'm wondering if I am using a feature that doesn't exist in that version

**Comment by maximkhatskevich** [comment]
xcodeproj --version
1.4.2

**Comment by jcampbell05** [comment]
So looks like it's related to the Entry code in https://github.com/CocoaPods/Xcodeproj/blob/0.28.1/lib/xcodeproj/scheme/build_action.rb

**Comment by jcampbell05** [comment]
Adding this to 0.8.9

**Comment by maximkhatskevich** [comment]
I trust you :)

**Comment by maximkhatskevich** [comment]
Thx for quick response!

**Comment by jcampbell05** [comment]
No worries, I'm hoping 0.8.9 will be a much better experience for you :) sorry for the pain.

**Comment by jcampbell05** [comment]
So this should be fixed by the latest version on master, I've found that ruby can select the wrong version of xcake so you should remove all older versions before running it :)
