### ISSUE TITLE
Crash using copy_files_build_phase

### ISSUE THREAD

**Issue by earien** [jcampbell05/xcake#158]
I've just tried using the brand new `copy_files_build_phase` method, but I get the following error:
```/Library/Ruby/Gems/2.0.0/gems/xcake-0.8.9/lib/xcake/dsl/build_phase/copy_files_build_phase.rb:19:in `block in configure_native_build_phase': undefined local variable or method `context' for #<Xcake::CopyFilesBuildPhase:0x007fa4c88c0860> (NameError)```

PS: there seems to be a typo in the `Cakefile.md` file: `copy_files_phase` should be `copy_files_build_phase`.

**Comment by jcampbell05** [comment]
Thanks for the catch I'll add it to our next release 0.8.10
