### ISSUE TITLE
undefined method `deep_merge'

### ISSUE THREAD

**Issue by aleph7** [jcampbell05/xcake#162]
Just installed the latest version (0.8.9) using ruby 2.3.3 and I get this error.

<details>

```
/Users/al/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xcake-0.8.9/lib/xcake/constants.rb:3:in `<module:Constants>': undefined method `deep_merge' for #<Hash:0x007f9834b2fa88> (NoMethodError)
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xcake-0.8.9/lib/xcake/constants.rb:2:in `<module:Xcake>'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xcake-0.8.9/lib/xcake/constants.rb:1:in `<top (required)>'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xcake-0.8.9/lib/xcake.rb:12:in `<top (required)>'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/al/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/xcake-0.8.9/bin/xcake:3:in `<top (required)>'
	from /Users/al/.rbenv/versions/2.3.3/bin/xcake:22:in `load'
	from /Users/al/.rbenv/versions/2.3.3/bin/xcake:22:in `<main>'
```

</details>

**Comment by jcampbell05** [comment]
interesting, looks like the polyfill may not be applies, do you have a project you can upload that reccreates the issue?

**Comment by aleph7** [comment]
I was trying to create a project I literally ran `gem install xcake; xcake init`

**Comment by steveholt55** [comment]
i'm also seeing this issue, just creating a new project `xcake init` is giving me this error

> /Users/brandon/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/lib/xcake/constants.rb:3:in `<module:Constants>': undefined method `deep_merge' for #<Hash:0x007f9534089ca8> (NoMethodError)
	from /Users/brandon/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/lib/xcake/constants.rb:2:in `<module:Xcake>'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/lib/xcake/constants.rb:1:in `<top (required)>'
	from /Users/brandon/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/lib/xcake.rb:12:in `<top (required)>'
	from /Users/brandon/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/bin/xcake:3:in `<top (required)>'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/bin/xcake:22:in `load'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/bin/xcake:22:in `<main>'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/brandon/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jcampbell05** [comment]
Interesting, what OS are you running?

**Comment by steveholt55** [comment]
macOS 10.12.4

**Comment by steveholt55** [comment]
Using xcake version 0.7.1 seems to work fine, no error, but anything newer than that is when I get the deep_merge error

**Comment by jcampbell05** [comment]
@steveholt55 Thanks for narrowing it down :) I'll see what caused the regression.

**Comment by RikkiGibson** [comment]
I had the same problem and also fixed it by installing version 0.7.1. Would like to know when there'll be a fix or anything.

**Comment by vitorventurin** [comment]
I have the same issue here. Why did you guys close it?

**Comment by jcampbell05** [comment]
It's fixed in master branch I'll push up another update as we probably just haven't released it
