### ISSUE TITLE
Incorrect scheme generated for extension target

### ISSUE THREAD

**Issue by RikkiGibson** [jcampbell05/xcake#165]
I'm using the `extension_for(target)` function to create an App Extension target based on my iOS app target. When I try to run one of the generated schemes for the App Extension, I get the error: "App Extension with identifier (bundle identifier) is already installed, so we can't install User App with that same identifier.".

When I simply select New Scheme and pick my App Extension target for the scheme, a working scheme is generated.

The differences I notice between the working and non-working in the UI include:

1. The working scheme has Executable set to "Ask on Launch"
2. "Expand Variables Based On" is set to my main app target.

**Comment by jcampbell05** [comment]
Are you still able to provide a project file with the working target and the xcake generated one so I can see what it is doing wrong ?

**Comment by RikkiGibson** [comment]
The error message is different in Xcode, but it's still broken. If you pull down this branch of my project and follow the instructions to build in README.md I think you'll be able to repro the problem.

https://github.com/rikkigibson/corvallis-bus-ios/tree/XcakeScheme

Let me know if it's excessively cumbersome or anything to deal with my whole project and I can try to just construct a simple project with an extension target for you to experiment with.

**Comment by jcampbell05** [comment]
So all other issues for new release fixed except this one - I am looking to see if the bundle identifier is being generated correctly with xcake.
