### ISSUE TITLE
How to set Gather Coverage Data flag to YES using Cake

### ISSUE THREAD

**Issue by thiagolioy** [jcampbell05/xcake#166]
Hello, i'd like to know if it is possible to set the "Gather Coverage Data" to yes on my scheme.

**Comment by RikkiGibson** [comment]
It seems like customizing schemes is pretty limited in Xcake at this time. I'm interested in more features in this vein as well.

As a workaround, you may want to consider adding an after_save handler that replaces the Xcake generated .xcscheme files with schemes that do what you want. Just modify Xcake's generated schemes to be how you want, copy them somewhere outside of your .xcodeproj, then run a script to copy them back in.

```ruby
project.after_save do |project|
    system "your shell command here"
end
```

**Comment by jcampbell05** [comment]
So we can probably add these flags if and when requested, will add this in 0.8.11
