### ISSUE TITLE
Supporting multiple ios app targets

### ISSUE THREAD

**Issue by colinta** [jcampbell05/xcake#169]
I am building a client / server game (ipad is the server, and iphones run the client).  For now I can merge these into one app (prob a good idea anyway), but it would be neat if we could support the ability to build multiple ios apps from one project.

**Comment by jcampbell05** [comment]
@colinta I think you can define two targets in xcake already :) and it should work fine.

**Comment by colinta** [comment]
You're right!  I had mistakes in my Cakefile.  Usually I override the default naming `target-config_type` (`App-Debug`) to be shorter, and this was clobbering the targets.

```ruby
    target.scheme c.name do |s|
        s.test_configuration = c.name
        s.launch_configuration = c.name
        s.profile_configuration = c.name
        s.analyze_configuration = c.name
        s.archive_configuration = c.name
    end
```

☝️ this names the configurations simply `Debug` or `Release`.
