### ISSUE TITLE
cannot load such file -- Xcodeproj (LoadError)

### ISSUE THREAD

**Issue by vitorventurin** [jcampbell05/xcake#170]
I've got this error:

>xcake make
/Users/Rotiv/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- Xcodeproj (LoadError)
	from /Users/Rotiv/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/lib/xcake/xcodeproj_ext/PBXGroup.rb:1:in `<top (required)>'
	from /Users/Rotiv/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Rotiv/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/lib/xcake.rb:9:in `<top (required)>'
	from /Users/Rotiv/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/Rotiv/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/gems/xcake-0.8.9/bin/xcake:3:in `<top (required)>'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/bin/xcake:22:in `load'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/bin/xcake:22:in `<main>'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Rotiv/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

:(

**Comment by RikkiGibson** [comment]
Not sure what to make of it. Did you poke around to see if Xcake's dependencies installed correctly? Did you install Xcake using `gem` or some other means?

**Comment by jcampbell05** [comment]
@RikkiGibson  whats your rubygem email btw, I'm gunna add you to it as an author.

**Comment by vitorventurin** [comment]
@RikkiGibson Yes. I've installed via gem (using RVM and ruby 2.4.0). That's really weird.

**Comment by RikkiGibson** [comment]
@jcampbell05 It's rikkigibson [at] gmail [dot] com

**Comment by jcampbell05** [comment]
@RikkiGibson  you should be added so you can push versions up :)

**Comment by earien** [comment]
@RikkiGibson @vitorventurin @jcampbell05 I had the same problem, it is due to the import in the `lib/xcake/xcodeproj_ext/PBXGroup.rb` file.
Changing it to `require 'xcodeproj'` instead of `require 'Xcodeproj'` fixed my problem: probably this works anyway on case insensitive systems, so that it is hard to reproduce.

**Comment by jcampbell05** [comment]
@earien  cool, I guess we should add this to our linting tests.

**Comment by RikkiGibson** [comment]
Does that mean if you use hfs case sensitive on your mac you'd trigger the issue?

**Comment by earien** [comment]
@RikkiGibson basically you won't notice the issue if you are using a case insensitive filesystem, whilst it will fail on a case sensitive one. 
We should fix the import in the `lib/xcake/xcodeproj_ext/PBXGroup.rb` file, as actually the correct name of the library is lowercased: `require 'xcodeproj'`.
