### ISSUE TITLE
How to create Cakefile from existing Xcode project?

### ISSUE THREAD

**Issue by ERbittuu** [jcampbell05/xcake#177]
I want to create "Cakefile" from my existing project and manage some information about the project.

**Comment by RikkiGibson** [comment]
It's definitely a feature we'd love to have. For now, it's necessary to manually create the Cakefile by inspecting key sections of the .pbxproj file. The files under docs/ in the repo may help you.

**Comment by ERbittuu** [comment]
OK, Thanks.
