### ISSUE TITLE
Ignoring xcassets

### ISSUE THREAD

**Issue by eiditakahashi** [jcampbell05/xcake#178]
Hi guys, since `v0.8.0` xcake is not including `.xcassets` in the project. Is this a bug or is there another way to include this extension ?

Part of my cakefile that includes files: `target.include_files = ["Common/**/*.*", "App/**/*.*"]`
Folder where xcassets is located: `Common/Resources/`
There are two more files with it and they are included.

**Comment by jcampbell05** [comment]
Can you try explicitly declaring you want the `xcassets`, but yes this is a bug

**Comment by eiditakahashi** [comment]
@jcampbell05 I tried this:
```
target.include_files = ["Common/**/*.*", "App/**/*.*"]
target.include_files << "Common/Resources/Images.xcassets"
```
and this:
```
target.include_files = ["Common/**/*.*", "Common/Resources/Images.xcassets/*.*", "App/**/*.*"]
```
with no success 😞 any suggestion?

**Comment by RikkiGibson** [comment]
Looks like the fix was committed but not yet published.

**Comment by jcampbell05** [comment]
Will publish along with another fix for UI Tests
