### ISSUE TITLE
Rename "debug" and "release" to match Xcode

### ISSUE THREAD

**Issue by petester42** [jcampbell05/xcake#18]
When Xcode creates a project the names for debug and release are capitalized like so "Debug" and "Release". I've found that some of my scripts to build applications using xcodebuild don't work since they rely on passing the configuration which was either "Debug" or "Release". 

It might be a good idea to keep these names consistent with Xcode.

**Comment by jcampbell05** [comment]
Good Idea. So the Project structure resolver is what provides the defaults configurations if you don't specify any. It should be a two line fix for us to capitalize it :)

**Comment by jcampbell05** [comment]
@petester42  Hey could you check this out and see if it works for you https://github.com/jcampbell05/xcake/pull/19
