### ISSUE TITLE
Build rule support?

### ISSUE THREAD

**Issue by Piasy** [jcampbell05/xcake#180]
Thanks for such a great tool!

I'm using J2ObjC, which need define custom build rule, does xcake support define custom build rule in Cakefile?

Thanks!

**Comment by jcampbell05** [comment]
@Piasy yes you can read about it here https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md#shell-script-build-phase

**Comment by Piasy** [comment]
Thanks for your quick reply, after a lot of google search and test, it seems that `build phase` and `build rule` are different.

J2ObjC use `build rule` to compile Java source, and the transpiled ObjC source need to compile and link with other sources in my project.

I try to invoke j2objc in build phase, it could generate ObjC sources, but these generated sources aren't compiled and linked with other sources.

Do I miss something or I need generate build rule?

**Comment by jcampbell05** [comment]
Interesting never used this feature when using this for iOS but I'll take a look. Could you create a very basic project for me ? 

Would be a big help in helping you to develop this feature.

**Comment by Piasy** [comment]
Sure, actually I'm working on such a project, https://github.com/Piasy/JavaUniverse
