### ISSUE TITLE
Settings.bundle read as folder

### ISSUE THREAD

**Issue by albyok** [jcampbell05/xcake#185]
I noticed now that xcake include file "*.bundle" as folders instead of files. Am I missing something? 

![image](https://user-images.githubusercontent.com/2544013/35094765-8d8be8ae-fc46-11e7-84a7-1d3922e38d71.png)

With a classic project I used to see bundles in this way:

![image](https://user-images.githubusercontent.com/2544013/35094814-be37d9cc-fc46-11e7-80b4-ff17b5e0379c.png)

And I could attach them to targets.

**Comment by albyok** [comment]
I'm now using this code to include the Settings.bundle, but it's clearly not the best practice. I also have now two copies of that file. One as folder and one correctly stated as bundle file.

`settingsBundlePath = "target_files/" + target.name + "/Settings.bundle"

    target.copy_files_build_phase "Copy Phase - Settings Bundle" do |phase|
  		phase.files = [settingsBundlePath] # array
  		phase.destination = :resources # can be any of `Constants::COPY_FILES_BUILD_PHASE_DESTINATIONS.keys`
  	end`

**Comment by jcampbell05** [comment]
I think there is a PR that fixes this and I'm about to release it :) since it effects things like xcassets.

**Comment by albyok** [comment]
Ok, perfect! Thanks for your great work again :-) 🥇

**Comment by jcampbell05** [comment]
Should be releasing this today :)

**Comment by jcampbell05** [comment]
:) oh forgot I released 0.8.10 already, will be 0.8.11 in that case :)

**Comment by albyok** [comment]
Ehi James. Is this fix still in progress? I'm sorry to bother you, but for me it would be very important

**Comment by jcampbell05** [comment]
Yeah it is :) will get this released today if thats okay ? :) hows you experience otherwise ? anything missing ?

**Comment by albyok** [comment]
All seemed fine, but I really need this fix. By the way, this script is really saving me, because I have a big project file that I'm sharing through a team and the merge was a pain in the ass.

This script should be integrated in Xcode. Try to contact Apple :D

**Comment by jcampbell05** [comment]
Glad to hear it :) Haha, I will try :)
