### ISSUE TITLE
Create source file with configuration params

### ISSUE THREAD

**Issue by ismetanin** [jcampbell05/xcake#187]
Hello! Is it possible to generate source file with some parameters from configuration? For example I want to create Fasfile with current app identifier and xcodeproj name.

**Comment by jcampbell05** [comment]
As in like a project template ?

**Comment by ismetanin** [comment]
@jcampbell05 Yeah, exactly

**Comment by jcampbell05** [comment]
So this tool is focused on generating projects, but I am working on one for project files.
