### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by sergeyzenchenko** [jcampbell05/xcake#2]
Hey James, we are working on same tool in our company. How we can help you with xcake?

**Comment by jcampbell05** [comment]
Sure, thanks for the offer :) How along is your tool ? And what things would you need xcake to do ? I am happy to review any PRs you do to help xcake along.

Currently I am focusing on getting Unit Tests into master, I have a working version but I am in the process of BDD Testing it and tidying it up.

**Comment by sergeyzenchenko** [comment]
I've started work on similar tool like a month ago, but had no time to finish it :(
We want to generate whole project infrastructure using DSL, NO xcode projects inside git :)

I had problems with xcassets and I found your lib from cocoapods issues list.

What's the status of static libs? We have huge project with like 12 subprojects. Each of them is static lib. So I'd like to generate them all.

**Comment by sergeyzenchenko** [comment]
btw, I thought about DSL in form of yml file, not ruby. So devs can't put any logic into it. But ruby based dsl works too.

**Comment by jcampbell05** [comment]
I understand the feeling I actually had a few prototypes of this a year ago but only now got around to open sourcing it and finishing it. I haven't built anything into the DSL for static libs but it should be straight forward enough to implement if you wanted to give it ago.

I started with Ruby DSL just as I was studying how cocoapods does it but I was actually thinking having a yml file may be a good idea as certain things are a challenge right now. Cocoapods actually both supports JSON and Ruby.

**Comment by sergeyzenchenko** [comment]
Merging and configuration management is hell in xcode :) We have like 11 developers working on same project.

**Comment by sergeyzenchenko** [comment]
So my goal is to move everything into custom DSL, not just project structure generation, but also build configurations.

**Comment by sergeyzenchenko** [comment]
Thi is @webzepter guy from my team. He is ruby dev who is helping with tools like this.

**Comment by sergeyzenchenko** [comment]
We will finish some other tools on this week and probable will have some time next week for xcake.

**Comment by jcampbell05** [comment]
Wow that is quite a lot; So the good news is, Xcake already supports Build configurations but I am aiming to abstract it a bit more than xcode. So your ocnfigurations not only contains your build settings but also your launch arguments (which will be used when generating the schemes).

I need to document this all for you guys. Awesome, the more the merrier!

**Comment by orta** [comment]
FWIW, I'd suggest _supporting_ but not making yaml the default, turing-complete languages config files work really, really well for projects like this / fast lane as there's a lot you should let the individual do instead of trying to make a mega-config file.

**Comment by jcampbell05** [comment]
@orta I agree and I will certainly keep that in mind. I love how cocoapods has achieved this. Podspecs can be in Ruby, JSON or YAML
