### ISSUE TITLE
Add command to create example cakefile from existing project.

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#29]
It's not clear how I can specify which files and under which groups/folders should be added to the project at the moment of creation, only basic project settings. Please clarify.

**Comment by jcampbell05** [comment]
For each target you specify the files to include and exclude, like so:

```ruby
Project.new do |project|
  project.application_for :ios, 8.0 do |target|

    target.name = "Sup"
    target.include_files  = "DifferentAppFolder/*.*"
    target.include_files << "OtherFolder/*.*"
    target.exclude_files << "FolderToIgnore/*.*"
  end
end
```
The syntax used to match file and folder paths is Ruby's Glob syntax - http://ruby-doc.org/core-1.9.3/Dir.html#method-c-glob

I've just noticed I missed those properties off in the documentation so thanks for pointing this out :)

**Comment by jcampbell05** [comment]
@maximkhatskevich  I've updated the documentation to explain the `include_files` and `exclude_files` properties.

https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md#include-files

Any issues let me know :)

**Comment by maximkhatskevich** [comment]
That’s great, thank you! What about brand new Xcode Assets catalog? it looks like file, but instead a folder. How do I specify that kind of file/folder in a Cakefile?

Also what are limitations of the Xcake? Is there something that I can not describe in Cakefile what is available in the *.xcodeproj file?


On January 8, 2016 at 01:12:30, James Campbell (notifications@github.com) wrote:

@maximkhatskevich I've updated the documentation to explain the include_files and exclude_files properties.

https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md#include-files

Any issues let me know :)

**Comment by jcampbell05** [comment]
Xcake should detect bundles and special folders such as Asset Catalogs or Core Data Models correctly and will add them to the project correctly. In the case of assets you just need to make sure your file pattern matches folders with the extension `.xcassets`.

Here is a list of the current support of Xcake https://github.com/jcampbell05/xcake/blob/master/docs/Xcode%20Project%20Support.md

It should be enough to get a comprehensive project file up and running. But if there is anything you need or think should be changed let me know and I'll be happy to add :)

**Comment by maximkhatskevich** [comment]
Sounds great! Thank you for quick answers.

One last question - is there a built-in tool/command to init Cakefile by reverse-engineering existing *.xcodeproj file so later I can continue controlling my project by just editing this file where it's needed? It would be also a very good starting point, an example to see how things should be expressed.

**Comment by jcampbell05** [comment]
@maximkhatskevich  Not right now but it's something I've gave a lot of thought to. There are a lot of things to consider (i.e How do we generate the patterns to match the files and folders)

I may prototype something up to see how we could pull it off. I do want to lower the barrier of entry though :) so a `cakefile init` command I think would really help.  so if you're willing to try it when I build it, then great!

**Comment by maximkhatskevich** [comment]
@jcampbell05 Sure, I would be glad to try it out when you have a beta! Feel free to let me know.

**Comment by maximkhatskevich** [comment]
@jcampbell05 but I think the command should be ```xcake init```.

**Comment by jcampbell05** [comment]
Yup it should, good catch ;)

**Comment by orta** [comment]
It is probably enough to give a worked replica, and then expect a developer to be able to take that and refactor it down with file/folder globbing patterns etc

**Comment by jcampbell05** [comment]
@maximkhatskevich  Going to start working on this shortly, I'll create a branch you can use to try this out.

**Comment by maximkhatskevich** [comment]
Wow, I look forward to it!

**Comment by menriquez** [comment]
@maximkhatskevich @jcampbell05 Really interested in this feature as I need the ability to add UITest targets and schemes dynamically to an existing xcode-built (Ionic) project...I was wondering if you guys believed this to be possible with Xcake and/or had any example code or references to how it could be done.

I am an IC who is working with a client who needs to build many (100s) of branded apps for retail clients, using Ionic and Fastlane, and the final blocker is having to attach a UITest target to the project in order to run Fastlane screenshot during Fastfile processing.

Thanks for all the hard work you guys have put into this project BTW...it looks great.

**Comment by maximkhatskevich** [comment]
@jcampbell05 my original question was a mix of 2 questions.
1) Sample Cakefile - this is done in #110 and #116.
2) Reverse-engineering Cakefile for a given existing Xcode project by calling something like "xcake init". First of all, this feature is actually not needed. It's better to take a look on sample Cakefile(s), write your own as well as re-organize project files and generate project file from that. Second, you currently implemented the "xcake init" and it just generates basic Cakefile which developer then can modify according to their needs.

So I think we can close this issue, it's resolved.

**Comment by maximkhatskevich** [comment]
@menriquez if I understood your question correctly, you are asking about how to configure UI tests for a target, right? If so - then please take a look on our sample Cakefile here (under "/example/app/" folder - you can find it directly here while it's not merged into main branch https://github.com/jcampbell05/xcake/tree/feature/example/example/app).

**Comment by maximkhatskevich** [comment]
@menriquez also please note, that currently UI tests are not working properly yet, we are working on it, here are the related issues #108 and #115.

**Comment by jcampbell05** [comment]
We should probably attempt to do something like this since this appears to have driven the traction of Struct

**Comment by maximkhatskevich** [comment]
@jcampbell05 agree, not having this functionality is the number 1 barrier for newcomers to start using our tool ASAP. It took me quite a while before I found some time to experiment with Xcake and migrate my project on Xcake manually.

**Comment by jcampbell05** [comment]
@maximkhatskevich awesome, I'll study how Struct does it to see if we can have any pointers :)

**Comment by maximkhatskevich** [comment]
Good idea!
