### ISSUE TITLE
How to add xcassets directory?

### ISSUE THREAD

**Issue by sergeyzenchenko** [jcampbell05/xcake#3]
Hey, how I can add xcassets to the project?

**Comment by jcampbell05** [comment]
So it should be included for your target automatically if its in the folder named after your target but you can make sure its included by making sure it matches the pattern specified for include_files

    Project.new do |c|
        c.application_for :ios, 8.0 do |t|
             t.name = "MyApp"
             t.include_files = "./myfiles/*.{c,swift,m,mm,xcassets}"
        end
    end

I hope this makes sense :) If it fails to include it properly then let me know, I've done some tidying up in that area :) should be an easy fix if it doesn't.

**Comment by sergeyzenchenko** [comment]
It's adding xcassets, but in form of regular folder, so XCode can't recognise it.

**Comment by sergeyzenchenko** [comment]
<img width="267" alt="screen shot 2015-11-25 at 9 19 56 pm" src="https://cloud.githubusercontent.com/assets/81555/11407252/4d6c6a92-93ba-11e5-8f9c-f5af857f8b76.png">

**Comment by jcampbell05** [comment]
Ah okay. I have a fix for this, I'll push it up tommorow.

**Comment by sergeyzenchenko** [comment]
Thanks!

**Comment by jcampbell05** [comment]
@sergeyzenchenko  Just pushed up a fix into master, please give it a try :)

**Comment by sergeyzenchenko** [comment]
Works now! Thanks!
