### ISSUE TITLE
Really interested - I have a few questions, though!

### ISSUE THREAD

**Issue by colinta** [jcampbell05/xcake#33]
I haven't delved into the code yet to see if there are easy answers, but I created a quick `XcakeTest` project and I'm playing with the Cakefile.

1. Info.plist - how does this file get created and configured?
2. Bridging Header - same question

**Comment by jcampbell05** [comment]
Good questions, right now this project mainly focuses on generating the Xcode project itself.

So for the Info.plist you have to provide it yourself. We default to assuming the Info.plist is located at "<target name>/Supporting Files/Info.plist" but you can override the build settings for this (`target.all_build_configurations.settings["INFO_PLIST"] = "location to plist"`). In the future we may make it easier to get setup with an example project which uses Xcake and contains the plists etc. 

For 2. you should be able to create a header file like normal and set the build setting (`target.all_build_configurations.settings["SWIFT_OBJC_BRIDGING_HEADER"] = "location to plist"`). In the future we may add some sugar to make it easier to set this build setting.

Let me know if this makes sense and anything you think could be done better.

**Comment by colinta** [comment]
Cool, I'll run with this.  I used RubyMotion for years, and always *really really* loved the way it managed all the aspects of the Xcode project.  For instance, it generated `Info.plist` based on the application settings (configured in a `Rakefile`).  Xcake is closer to the metal, which is a good place to start I think.  I might take a stab at providing an Info.plist generator as a 3rd party thing...

**Comment by colinta** [comment]
Shoot, next question!  Build Phases.  How do they work? :smiley:

**Comment by colinta** [comment]
Ok, looked through the `build_phase/` code, I *don't* see something that would help me migrate a custom build script.

e.g.
```
		763D32411A939F4600AA1AA1 /* Start Fabric/Crashlytics */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
			);
			name = "Start Fabric/Crashlytics";
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "./Pods/Fabric/Fabric.framework/run 8cfa59e7bc00ac6272cdd11f6ff37d1513e617d6 118d575c7a6751062e0aa49fa140e80d12cc1e1ff4d8522133dd863578414dd6";
		};
```

**Comment by jcampbell05** [comment]
So right now the build phases are inferred, that is we look at the files you want to include, the target types and we generate the build phases accordingly. 

If you're looking to automate uploading to fabric then I would recommend @krausefx.https://github.com/fastlane/fastlane by @krausefx.

**Comment by colinta** [comment]
Well, that's not what this build phase does, but that part isn't even all that important.  Another example, we have a build phase that looks for `fit/fdescribe/fcontext` to warn about focused specs.

```
F872635E1AB08A5700FCB59D /* Generate warnings for focused tests */ = {
  isa = PBXShellScriptBuildPhase;
  buildActionMask = 2147483647;
  files = (
  );
  inputPaths = (
  );
  name = "Generate warnings for focused tests";
  outputPaths = (
  );
  runOnlyForDeploymentPostprocessing = 0;
  shellPath = /bin/sh;
  shellScript = "KEYWORDS=\"fdescribe|fcontext|fit\"\nFILE_EXTENSIONS=\"swift\"\nfind -E \"${SRCROOT}/Specs/\" -regex \".*\\.($FILE_EXTENSIONS)$\" -print0 | xargs -0 egrep --with-filename --line-number --only-matching \"($KEYWORDS)\\(.*\\$\" | perl -p -e \"s/(?:$KEYWORDS)\\(\\\"(.*)\\\".*/ warning: Focused Spec: \\$1/\"";
};
```

**Comment by jcampbell05** [comment]
Yeah we need to get custom build phases in, thanks for your PR. I'll take a look :)

**Comment by colinta** [comment]
Next question is about CocoaPods and the xcconfig files it generates.  Do you include those in your project somehow?  Or do you just add them to `include_files` manually?  A quick "do this if you use CocoaPods" would be awesome, it feels like I'm missing a crucial step.

Atm, it's not finding Crashlytics, which happens to be the first `import` in my AppDelegate (so I'm guessing other pods are "missing" as well.

**Comment by jcampbell05** [comment]
So right now we don't support XCConfig but I would love to in the future (even if its just the ability to set them for targets). 

You can use cocoapods today by running xcake and running pod install (I use it in our app which uses them together). There is one bug I am working on fixing where if you overwrite a project integrated with cocoapods using xcake it loses the xcconfigs set in the project, so you have to run pod install again. In the future we may xcake a bit more intelligent about overwriting existing projects. Maybe in the far far future the podfile could be specified in the `Cakefile` via a plugin.

Definitely need some manuals on cocoapods and carthage.

**Comment by jcampbell05** [comment]
@colinta  let me know if you get it working or not :)

**Comment by colinta** [comment]
I was able to get past `import Crashlytics`, but the simulator never booted up.  Odd.  I have to put this down for now, I'll get a chance to work on it again on Wednesday.  Thanks!

**Comment by jcampbell05** [comment]
@colinta  no worries. I hope we can solve that.

**Comment by colinta** [comment]
Using my recent PRs I'm able to build and run tests.  Running `pod install` was essentially setting the xcconfig, which I wanted to do via Xcake so I *don't* have to run pod install every time.

**Comment by jcampbell05** [comment]
@colinta Yeah I want to update xcake so you can set these and maybe in the future it could merge into an existing project if you preferred that behavior.

or thinking longer term I was thinking of integrating cocoapods into xcake via the plugin system it has :)

**Comment by kirakik** [comment]
@jcampbell05 just following up because I haven't seen anything related to custom build scripts in the documentation, is there currently any way to include them?

**Comment by jcampbell05** [comment]
@kirakik There is a way to add a build script phase here - https://github.com/jcampbell05/xcake/pull/97
