### ISSUE TITLE
`class_prefix=` and `project_name=` and `organization=` don't get assigned to `Project` instance

### ISSUE THREAD

**Issue by colinta** [jcampbell05/xcake#36]
In the Cakefile,
```ruby
project_name = "Ello"
class_prefix = "Ello"
organization = "Ello"

debug_configuration :Debug
release_configuration :Release
```

These have no effect on the `Project` instance, because this assignment looks like a local variable assignment.  In the short term I replaced these with `self.project_name=`.

**Comment by jcampbell05** [comment]
Yeah in an earlier version you had to write the following which worked:

```ruby
Project.new do |project|
project.class_prefix = "Ello"
end
```

We could return to this or we could do something simpiler such as :+1: 

```ruby
Project do |project|
project.class_prefix = "Ello"
end
```

or just

```ruby
project.class_prefix = "Ello"
```

**Comment by colinta** [comment]
Interesting... another thought, might be a bit too "magic":

```ruby
file_contents = File.read(file_path)

file_contents << <<-MORE

if defined?(project_name)
  self.project = project_name
end

MORE

project = Project.new
project.instance_eval(file_contents)
```

**Comment by colinta** [comment]
Instead of `Project do` I think that `project do ...` would be a good place to put these project configurations.  It matches well with `target do ...`.

```ruby
project do |p|
  p.project_name = "Ello"
  p.class_prefix = "Ello"
  p.organization = "Ello"
end

debug_configuration :Debug
release_configuration :Release

application_for :ios, 8.0, :swift do |target|
```

**Comment by colinta** [comment]
Final call is up to you, I was just reporting the error.  Happy to brainstorm, though!  The `Project.new` or `Project do` syntax seems off to me (am I creating a *new* project?), but as a plain method it makes sense.  I wouldn't be opposed to using a file-wide `Project.create do` wrapper, either (that's how it works in RubyMotion actually).

You *could* even encourage `@project_name = "foo"`, but that does not seem ideal.

**Comment by colinta** [comment]
Actually, I think I like the `defined?(project_name)` code the most!  It offers a succinct Cakefile.  You'd have to maintain a white list of properties.

```ruby
file_contents = File.read(file_path)

local_vars = [:project_name, :class_prefix, :organization]
local_vars.each do |var_name|
  file_contents << <<-MORE

self.#{var_name} = #{var_name} if defined?(#{var_name})
MORE
```

**Comment by jcampbell05** [comment]
So the file wide wrapper or method would be more explicit but could intro some boilerplate. On the other hand it could be more understandable especially for people coming from Rubymotion

We could instead whitelist or introduce methods to configure the project like you have suggested. The project in general has fewer things to configure so I think it is acceptable.

I really like what @orta, @segiddins and the team did with Cocoapods when specifiying the OS a project is for. 

platform :ios, '9.0'

Most of their configuration syntax is method based 
though so White listing properties may work for us.

Main concerns for me is fragility and also how obvious these are magic properties. 

But I suppose given the minimal amount of configuration these properties are unlikely to be used for anything but configuration (I.e the user isn't going to declare their own local variables named the same thing)

**Comment by jcampbell05** [comment]
I think I like those properties on further reflection

**Comment by jcampbell05** [comment]
So I've been thinking about this for a while and had a play around with it. I think exposing a project method would be the easiest.

```ruby
project do |p|
  p.project_name = "Ello"
  p.class_prefix = "Ello"
  p.organization = "Ello"
end
```

Whitelisting I think would require the author of the Cakefile to be aware of those special properties and for us to also whitelist them. I think the method is a good tradeoff (2 extra lines).

And as you point out it is consistent with what we already have :).

**Comment by jcampbell05** [comment]
Thanks for brainstorming with me, really helped to nail down something! :)

**Comment by colinta** [comment]
Cool! I dig it! Happy to help! 😆
