### ISSUE TITLE
Helper method for generating UI Test targets?

### ISSUE THREAD

**Issue by kdawgwilk** [jcampbell05/xcake#44]
I saw there is a helper method to add a unit test target for an app but I was wondering if there is one for UI test targets as well

**Comment by jcampbell05** [comment]
I haven't added one yet but I will add this in the next release coming out this week. When will you need this by?

**Comment by kdawgwilk** [comment]
I have been working on a project template setup script and was checking out xcake to help with reducing merge conflicts for future template projects. No rush!

**Comment by jcampbell05** [comment]
@kdawgwilk so if I add a `ui_tests_for <target>` method would this be a good syntax for you ?

**Comment by maximkhatskevich** [comment]
@jcampbell05 what's the status on creating UI tests target using Xcake? I'm going to include the "ui_tests_for <target> ..." syntax into the sample Cakefile I'm preparing now, okay?

**Comment by jcampbell05** [comment]
@maximkhatskevich The code is merged into `master` the documentation just needs updating, that will be a big help thank you (y)

**Comment by maximkhatskevich** [comment]
Okay, I'm going to mention this in the docs then.

**Comment by maximkhatskevich** [comment]
@jcampbell05 pushed docs update to the same branch, see above ^^
