### ISSUE TITLE
Unable add folder references and static libraries

### ISSUE THREAD

**Issue by Nodepad** [jcampbell05/xcake#45]
Currently I can't add folder reference to the project. I think it happens because of following lines in file `copy_resources_build_phase.rb`.
```
def self.can_install_node(node)
  !File.directory?(node.path)
end
```
Also third party static libraries is automatically added to copy resource build phase and as I understood there is no way to add them to Link with static library build phase.
Also I think there is no way to create custom build phase too?

**Comment by jcampbell05** [comment]
Custom build phases is being added into 0.6.x which should be released fairly soon. Which phases would you need?

We don't support folder references yet but I can add this for you if you like as well as tweaking static libraries to be added to the correct phase ?

**Comment by Nodepad** [comment]
I need to add custom shell script for crashlytics. Probably it even can be added to 'after save' hooks, but this is for later.
I'd like working folder references. About static libraries, maybe it's better to give user more flexible api to add static libraries, not just add all libraries to correct phase?
I'm working on continuous deployment (fastlane) for iOS project and think it will be good to use xcake for recreation of xcodeproj with multiple targets for it. If it will be added in two weeks it'll awesome. I could write some of these fixes myself but as I understood there is version 0.6 coming, so some api will change.

**Comment by jcampbell05** [comment]
@Nodepad So most of the API changes are complete so feel free to pull down master and try and implement the fixes yourself :)

**Comment by jcampbell05** [comment]
@Nodepad 0.6.0 is released now so it should be safe to add this. What would be the ideal syntax for you ?

**Comment by jcampbell05** [comment]
Thanks for your PR :)

**Comment by RikkiGibson** [comment]
It looks like support for folder references is in, but I can't find documentation for it. How does it work?

**Comment by RikkiGibson** [comment]
D'oy, I figured it out. You just have to add a path to a folder to `target.include_files`, and that folder will get added as a folder reference instead of as a group.

**Comment by jcampbell05** [comment]
@RikkiGibson  exactly :) I'll up date the documentation
