### ISSUE TITLE
XCconfig issues with Cocoapods

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#52]
Xcake modify these settings somehow so cocoapods doesn't always want to integrate its xcconfigs.

**Comment by therealbnut** [comment]
IIRC Cocoapods supports the following:
 * `$(inherited)` in settings, you can fall back from a target config to a project one.
 * Including the pod xcconfig from your own xcconfig:
```c
#include "Pods/Target Support Files/Pods/Pods.debug.xcconfig"
```
This should let you use both Cocoapod and Xcake `.xcconfig` files.

**Comment by jcampbell05** [comment]
Awesome I'll add some documentation about this !

**Comment by jcampbell05** [comment]
@therealbnut would you like to join our team of contributors ?

**Comment by therealbnut** [comment]
That'd be great, thanks :) I'm actually just working on a PR...

**Comment by jcampbell05** [comment]
@therealbnut  awesome I've added you, welcome to the team!

**Comment by therealbnut** [comment]
thank you :)

**Comment by jcampbell05** [comment]
It will be good to see if we can do something similar the way @lyptt is planning to do it in Struct https://github.com/lyptt/struct/issues/7
