### ISSUE TITLE
Add more committers to Xcake.

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#57]
After reading up on @ashfurrow 's really great blog post on how building a community is great for open source. I took a look at how Artsy did that for Moya.

I too don't want Xcake to die and for it to continue to be used in the Long run.

What I'm looking for is people who can:

Reply to questions.
Help diagnose/fix issues people have.
Help form a roadmap for future releases.
All when you have time and feel like it. It's not meant to be a burden.

Don't ever feel bad for not contributing to open source. —@alloy

If you're interested in helping out – when it's convenient for you – comment on this issue and I'll add you as a committer with push access.

/cc @colinta @orta @ashfurrow @Nodepad @roger-tan @alexsup @petester42

**Comment by Nodepad** [comment]
Hi, I'm interested to contribute to xcake. I don't have much time right now, but I want to contribute.
From my perspective xcake needs two feature to add in near future:
* Ability to add folder references
* Handling of localised resources
I'll try to make pr for first feature this week.

**Comment by jcampbell05** [comment]
@nodepad Awesome! I'll add you to my contributors :) :rocket:

**Comment by petester42** [comment]
Sounds good. I'll help out when I have time.
