### ISSUE TITLE
HOW-TO Configure unit test target

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#60]
It's not clear at all how do I configure Unit Test target. There is only one mention of unit tests in documentation currently: 

http://www.rubydoc.info/github/jcampbell05/xcake/master/file/docs/Cakefile.md#Tests

I need to be able to control at least it's name and it's files location. Ideally I would like to be able to configure it the same way I can configure application target. Right now by placing 'unit_tests_for target' in 'Cakefile' I'm just getting an empty unit tests target associated with my app target, and that's it. It's empty and useless. Please, clarify.

**Comment by maximkhatskevich** [comment]
Any comments on this please?

**Comment by petester42** [comment]
More helpful info can be found at https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md under the targets section.

**Comment by maximkhatskevich** [comment]
@petester42 I've learned all documentation, but didn't understand how I can configure the unit test target, or, moreover, multiple unit tests targets. Could you please give me an example or give me some more details? I would really appreciate that.

**Comment by maximkhatskevich** [comment]
@petester42 Do you mean this section https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md#tests ?

**Comment by petester42** [comment]
Yes

**Comment by maximkhatskevich** [comment]
What is says is that the target is going to have a complementary unit tests target, but I have no idea how to control this unit tests target name, properties, include files, have multiple unit tests targets for the same application target.

**Comment by petester42** [comment]
I'm pretty sure you can do this

```
unit_tests_for_target target do |test_target|
    // edit test_target like a normal target
end
```

**Comment by maximkhatskevich** [comment]
Wow! Probably if I would know Ruby more - it would be obvious for me, but I'm iOS dev. Okay, thanks, let me try!

**Comment by maximkhatskevich** [comment]
@petester42 Awesome! That works, thank you so much! I'm going to submit a pull request for this as well. Note: you should use `unit_tests_for` instead of `unit_tests_for_target`.

**Comment by petester42** [comment]
No problem. Thanks for documentation update in advance :)
