### ISSUE TITLE
Minor issue in documentation

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#61]
Their is a minor issue in documentation.

According to documentation, to include files into a target we should do like this (http://www.rubydoc.info/github/jcampbell05/xcake/master/file/docs/Cakefile.md#Include_Files):

`
target.include_files = "DifferentAppFolder/*.*"
target.include_files << "OtherFolder/*.*"
`

in fact it does not work at all, the `<<` operator leads to empty target (no files included at all). After consulting with our Ruby developer, I found out that we should instead do like this:

`
target.include_files = ["Libs/**/*.*"]
target.include_files << "Src/**/*.*"
`

that means that `include_files` is an array, so when we use `=` we have to provide an array of strings as initial value, and then later we can add items (strings) into array, one at a time, using `<<` operator.

**Comment by jcampbell05** [comment]
Great catch @maximkhatskevich, could you submit a PR to fix this ?
