### ISSUE TITLE
Ambiguity about how we access/set configuration build settings

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#65]
In this file https://github.com/jcampbell05/xcake/blob/master/docs/Cakefile.md we can find 2 different ways f doing the subject:

`configuration.settings["KEY"] = "VALUE"`

and

`configuration.build_settings["ENABLE_BITCODE"] = false`

The question is what is the right way? If both supported - we should deprecate one and go for another one (I'm down for the shortest one), to avoid confuses. Please let me know, so I can update documentation. I personally use just `configuration.settings` and it works well.

**Comment by jcampbell05** [comment]
I think we should just use `settings`, I believe `build_settings` is for an earlier version of the tool.

**Comment by jcampbell05** [comment]
This should be fixed in the documentation on master.
