### ISSUE TITLE
How do you add `.xcconfig` files to a project?

### ISSUE THREAD

**Issue by therealbnut** [jcampbell05/xcake#66]
I've read the tests and much of the source code, however I don't seem to be able to get `.xcconfig` files working. Looking at #62 they seem to be implemented.

My `Cakefile` has this line:

     project.all_configurations.configuration_file = "Base.xcconfig"

I'm expecting to see something set here:

<img width="488" alt="screen shot 2016-05-02 at 10 42 49 pm" src="https://cloud.githubusercontent.com/assets/635596/14954640/5e0bc954-10b7-11e6-8788-4a919b192024.png">

**Comment by jcampbell05** [comment]
As long as the string you set points to a Xcconfig file they should work.

Which version of xcake are you using and could you send your cake file so I can recreate

**Comment by therealbnut** [comment]
xcake `0.6.7` installed via `bundler` on OSX.

**Cakefile:**
```ruby
# set_trace_func proc { |event, file, line, id, binding, classname|
#   printf "%8s %s:%-2d %10s %8s\n", event, file, line, id, classname
# }
application_for :ios, 8.0 do |target|
  target.name = "YourApp"
  target.all_configurations.configuration_file = "Base.xcconfig"
end
```

**Base.xcconfig** (in the same directory):
```
MY_USER_SETTING="EXAMPLE"
```

**Comment by jcampbell05** [comment]
@therealbnut thanks, I'll see if I can recreate this and issue a bug fix.

**Comment by therealbnut** [comment]
Let me know if you want the `Gemfile.lock` or anything like that.

**Comment by therealbnut** [comment]
It's still WIP, but this branch seems to address the issue for me:
https://github.com/jcampbell05/xcake/compare/therealbnut-adjust-xcconfig
It seems strange that it ever worked, so it would be good if you could verify if the old code works works for you @jcampbell05. Also whether or not this fixes it for you :)

It's quite possible I've got some weirdness in my setup. I've done a lot of hacking around with xcodeproj in the past, it's possible I've somehow messed up my gems through my inexperience with ruby.

The issue seems to be two-fold, the `xcconfig` is added to the project, not the [configuration](http://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/Project/Object/XCBuildConfiguration#base_configuration_reference-instance_method).
```diff
- native_configuration_object.base_configuration_reference = xcconfig
+ build_configuration.base_configuration_reference = xcconfig
```

The test verified that, so it wasn't picked up:
```diff
- expect(@native_configurable).to receive(:base_configuration_reference=).with(xcconfig)
+ expect(@native_configuration).to receive(:base_configuration_reference=).with(xcconfig)
```

---

You may also be interested on that branch, I add this:
```diff
- project.instance_eval(file_contents)
+ project.instance_eval(file_contents, file_path)
```
It prints out nicer debugging info (the path of the Cakefile), when there's an error.

**Comment by jcampbell05** [comment]
For the `instance_eval` help identify the line of the Cakefile when there is an error, I'll check out the PR and give it a go.

**Comment by therealbnut** [comment]
I'm not 100% sure what you meant. However, `instance_eval` takes these arguments: `(code, [string identifying the file], [number for the first line])`. The line argument defaults to `1`, so I've left it off, the file string defaults to gibberish, so I've added the Cakefile path.

**Comment by jcampbell05** [comment]
Okay great :)

**Comment by jcampbell05** [comment]
Should be implemented in https://github.com/jcampbell05/xcake/pull/68
