### ISSUE TITLE
Xcode groups don't link to the corresponding directory

### ISSUE THREAD

**Issue by madbat** [jcampbell05/xcake#69]
Currently the project groups generated by Xcake are not set to match the corresponding directory in the filesystem.
Is there anything preventing Xcake from setting a PBXGroup's path attribute to point to its directory?

**Comment by jcampbell05** [comment]
@madbat I believe we have some code that should do this but clearly it's not working. It should be as simple as just setting that attribute, there is no reason it couldn't do this.

You are welcome to submit a PR.

**Comment by madbat** [comment]
@jcampbell05 cool, I'll try 👍

Do you have any pointers on where to look?

**Comment by jcampbell05** [comment]
@madbat  This is the method where we take a path to a folder and create a group.

https://github.com/jcampbell05/xcake/blob/master/lib/xcake/xcode/project.rb#L129
