### ISSUE TITLE
Specify Frameworks (including third-party ones) to be included in the project/target

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#70]
Is there a way to do so? Something like this:

target.all_configurations.frameworks = ["UIKit"]
target.all_configurations.frameworks << "CoreLocation"
target.all_configurations.frameworks << "Src/Frameworks/FacebookSDK/FacebookSDK.framework"

**Comment by jcampbell05** [comment]
@maximkhatskevich  `system_frameworks` should allow you to add a system library if you set it like so:

```
target.all_configurations.system_frameworks = ["UIKit"]
```

**Comment by maximkhatskevich** [comment]
System frameworks seem to be adding automatically, the biggest question for me is how to add 3d party frameworks by specifying path explicitly? TO not do it manually by drag-n-drop after you re-generated xcodproj file.

**Comment by jcampbell05** [comment]
@maximkhatskevich  You should be able to specify framework paths in the `include_files` property that adds the file. Xcake will detect its a framework and add it to the correct phase.

**Comment by maximkhatskevich** [comment]
This was my initial assumption, but no. It adds it just as regular source files, and adds frameworks as folders, while they are not presented in "Frameworks" section.

**Comment by jcampbell05** [comment]
Ah okay thats a bug, can you upload me a example project recreating the problem ?

**Comment by maximkhatskevich** [comment]
Okay, will do

**Comment by maximkhatskevich** [comment]
Here is example project. First of all, it adds "Info.plist" file to "Copy bundle files" phase, even if I set explicitly path to info file. Download Facebook SDK (https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip)
 and unarchive under "Frameworks" folder. Uncomment line 20 in Cakefile and re-generate project file to see how it will add framework as regular folder.

[XcakeFrmTest.zip](https://github.com/jcampbell05/xcake/files/266806/XcakeFrmTest.zip)

**Comment by jcampbell05** [comment]
@maximkhatskevich  Sorry for slow response, I'll run this and see if I can get a fix :)

**Comment by maximkhatskevich** [comment]
Thank you! I look forward to your updates.

**Comment by maximkhatskevich** [comment]
@jcampbell05 any updates on this? This is important as well. Can you reproduce that issue? It adds Frameworks as folders, not as frameworks.

**Comment by jcampbell05** [comment]
I've got it on my desktop :) going to give it a go.

**Comment by maximkhatskevich** [comment]
Cool, thanks! Look forward to your update on this. For now I add frameworks manually after generating project file with Xcake.

**Comment by jcampbell05** [comment]
@maximkhatskevich  Really sorry about that, it sounds painful :(

**Comment by maximkhatskevich** [comment]
@jcampbell05 okay, when you fix this issue it will be clear how to include 3d party frameworks, but how do I specify non-default system frameworks in a target? By default Xcode include Foundation and UIKit, but I need to add AdSupport system framework. Any ideas? Thanks in advance!

**Comment by jcampbell05** [comment]
@maximkhatskevich You should be able to add it like so 

```
target.system_frameworks << "Another Framework"
```

**Comment by maximkhatskevich** [comment]
Yes, that works too! Thank you :) I'll put that into documentation as well.

**Comment by brennantaylor** [comment]
Any word on this? I imagine any sizable project includes 3rd party dependencies. This is a blocker for the project I am working on at the moment.

**Comment by maximkhatskevich** [comment]
@brennantaylor should not be a blocker, for now just add 3d party frameworks manually after you regenerated project. Usually you do not re-generate project very often, right?

**Comment by jcampbell05** [comment]
@brennantaylor Let me know if the work-around from @maximkhatskevich  isn't enougth for you and I'll try and get a fix up today.

**Comment by brennantaylor** [comment]
@maximkhatskevich Yeah that's what I've been doing. I add them as normal files and just uncheck and check the box in the target editor.

Right now we're trying to split up our project into smaller modules so I'm generating new projects over and over.

**Comment by jcampbell05** [comment]
@brennantaylor okay, sorry about that. Will work on a fix right away!

**Comment by jcampbell05** [comment]
Okay looked into how we do this, so currently this is the state of library support in Xcake:

- System Frameworks are added via `system_frameworks`
- System Static Libraries are added via `system_libraries`
- Third Party Static Libraries are automatically added and detected when you added them via the `include_files` property.

Currently as you have pointed out Xcake is lacking the code to do the same thing for Frameworks, I am currently implementing this :)

**Comment by maximkhatskevich** [comment]
Great, thanks!
