### ISSUE TITLE
Random errors during making project

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#76]
When I try to make even basic project (Cakefile: https://dl.dropboxusercontent.com/u/73350479/Cakefile) I'm getting errors like this:

![screen shot 2016-05-31 at 3 54 46 am](https://cloud.githubusercontent.com/assets/2624646/15659408/8047fbea-26e3-11e6-9d57-be7d96896170.png)

**Comment by maximkhatskevich** [comment]
Looks like errors in source code. Any ideas? Please help. How can I downgrade to previous stable version?

**Comment by jcampbell05** [comment]
Looks like there are some changes in Xcodeproj 1.0 which break Xcake. Do you have a project that I can have a look at to fix this?

You should be able to downgrade if you set the version in your Gemfile, if you use the `gem install` command you can also use the ` -v` flag.

**Comment by maximkhatskevich** [comment]
I figured out how to downgrade, tried few older versions, it does not help. You assumption might be right, it looks like issues in external dependency. What do you mean "Do you have a project that I can have a look at to fix this" - I'm not sure. I gave you Cakefile (see the link in my original post) that can not be processed by Xcake, so I do not have project yet (I can't generate even a very basic, empty Xcode project). Please, try to run "xcake make" with Cakefile I provided and see the errors. Please, let me know if it makes sense for you!

**Comment by jcampbell05** [comment]
@maximkhatskevich  I'll have a look, I should be upgrading my project soon to CocoaPods 1.0 so I'll be able to see these in mine too.

**Comment by maximkhatskevich** [comment]
It's kind of urgent, it blocked me yesterday from moving forward at work, so now I have to look for a workaround. I would very appreciate your help with this as soon as you can!

**Comment by maximkhatskevich** [comment]
Another example of output when I put some build settings configuration inside target:

![screen shot 2016-05-31 at 2 58 24 pm](https://cloud.githubusercontent.com/assets/2624646/15670703/a0c11f2c-2748-11e6-8b07-66e60992c37c.png)

**Comment by jcampbell05** [comment]
@maximkhatskevich  Were you setting those settings using `all_configurations` ?

**Comment by maximkhatskevich** [comment]
Yes, sure! My Cakefile was working absolutely fine, I didn't re-generate project for few weeks and now tried to do so without changing anything in Cakefile (but I upgraded to latest Xcake first and updated system, probably Xcode upgraded as well since my last usage of Xcake), and it failed.

**Comment by jcampbell05** [comment]
@maximkhatskevich Okay I think there was a PR I merged which potentially broke the settings for you. I'll update the docs but in my Cakefile I am doing this:

```
  target.all_configurations.each do |c|
      configuration.settings["ENABLE_BITCODE"] = "NO"
      <other settings....>
  end 
```

**Comment by maximkhatskevich** [comment]
I'll try in an hour this and let you know, but even if I use almost empty basic Cakefile there is anothere error - see my first posted screenshot, can you reproduce it on your end?

**Comment by jcampbell05** [comment]
@maximkhatskevich I'll give that a go, I've just updated to Cocoapods 1.0 and will be running the test suite.

**Comment by maximkhatskevich** [comment]
Thank you! I look forward to any updates on this from you :)

**Comment by maximkhatskevich** [comment]
@jcampbell05 after changing how I set build settings for "all_configurations" - everything works! Thank you very much!

**Comment by maximkhatskevich** [comment]
Let me know if you want me to update documentation, I would be happy to do so!

**Comment by jcampbell05** [comment]
@maximkhatskevich  that would be a huge help if you could :) sorry for not doing this myself.

**Comment by maximkhatskevich** [comment]
Okay, I'll do it. Not right now, but later today or tomorrow (until that you can forward everyone to this page). Hope that works!

**Comment by jcampbell05** [comment]
@maximkhatskevich  thats perfect, thank you for all of your feedback. Keep it coming!

**Comment by jcampbell05** [comment]
I think both of these issues should be fixed in master.
