### ISSUE TITLE
Does not set "PROVISIONING_PROFILE" at all

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#77]
Even if I specify correct profile identifier and it's available/downloaded in Xcode - the result project file does not have any explicit value for "PROVISIONING_PROFILE" setting and shows default "Automatic".

**Comment by jcampbell05** [comment]
@maximkhatskevich is this related to the configuration issues ?

**Comment by colinta** [comment]
It sounds to me like the value is just empty - my understanding is that it has to be set manually, e.g. `target.release_configuration.settings["PROVISIONING_PROFILE"] = "[provisioning profile id]"`

**Comment by jcampbell05** [comment]
@colinta  Yeah Xcake defaults to setting it to Automatic unless you specify it in the Cakefile as above.

@maximkhatskevich  Do you have an example Cakefile.?

**Comment by maximkhatskevich** [comment]
@jcampbell05 yes, it's 100% related to the issue about accessing configurations, it's not actual anymore. See the right way of accessing configuration settings in this thread https://github.com/jcampbell05/xcake/issues/78
