### ISSUE TITLE
Configuration-specific flags seems to be ignored

### ISSUE THREAD

**Issue by maximkhatskevich** [jcampbell05/xcake#78]
If I have something like this in my Cakefile:

`
target.debug_configuration :Debug do |configuration|
    configuration.settings["SWIFT_OPTIMIZATION_LEVEL"] = "-Onone"
end
`

Then this setting is not set in the result project file (stays default). 
![screen shot 2016-06-02 at 6 27 38 pm](https://cloud.githubusercontent.com/assets/2624646/15746369/b79b82d4-28ef-11e6-8449-d29fafc82108.png)

**Comment by jcampbell05** [comment]
@maximkhatskevich I've noticed this too. Does this work for the other settings like Release or does this effect them all.

This is the same project you gave me right ?

**Comment by maximkhatskevich** [comment]
All other settings seems to be working well, if I notice anything else - I'll report for sure. It's in my work project.

**Comment by maximkhatskevich** [comment]
@jcampbell05 it looks like any flags that I set per configuration are ignored by Xcake, they are not set after I run Xcake.

For example, I have this inside my target configuration:

target.debug_configuration :Debug do |configuration|

        #=== Common

        configuration.settings["VALIDATE_PRODUCT"] = "NO"
        configuration.settings["COPY_PHASE_STRIP"] = "NO"

        configuration.settings["ONLY_ACTIVE_ARCH"] = "YES"
        configuration.settings["ENABLE_TESTABILITY"] = "YES"
        configuration.settings["GCC_OPTIMIZATION_LEVEL"] = "0"
        configuration.settings["OTHER_CFLAGS"] = "$(inherited)"
        configuration.settings["ENABLE_NS_ASSERTIONS"] = "YES"

        # configuration.settings["DEBUG_INFORMATION_FORMAT"] = "dwarf-with-dsym" # "dwarf"
        configuration.settings["SWIFT_OPTIMIZATION_LEVEL"] = "-Onone"

        #=== Config

        configuration.settings["GCC_PREPROCESSOR_DEFINITIONS"] = "$(inherited) CONFIG_" + configuration.name.upcase + "=1" # Obj-C support
        configuration.settings["OTHER_SWIFT_FLAGS"] = "$(inherited) -DCONFIG_" + configuration.name.upcase # Swift support
    
        configuration.settings["PROVISIONING_PROFILE"] = "XXXX" # dev

        #=== Config - User Defined Build Settings
        
        configuration.settings["BRANCH_KEY"] = "YYYY"
        configuration.settings["FACEBOOK_KEY"] = "WWWW"
    end

**Comment by maximkhatskevich** [comment]
None of these flags are set in a freshly made project file for this target/configuration after I run Xcake. Please help. It looks like core functionality regression!

**Comment by jcampbell05** [comment]
Oooo yeah that defiantly looks like one. I'll work on a unit test for this as well as fixing the swift to no be optimised for non-release builds.

I wonder if its the way you're accessing the configuration too.

I've been able to override settings like BITCODE.

**Comment by maximkhatskevich** [comment]
It seems like it works when I access configuration like this:

target.all_configurations.each do |configuration|

        configuration.settings["ENABLE_BITCODE"] = "NO"

end

but it does not work when I access them later one by one like this:

target.debug_configuration :Debug do |configuration|

    configuration.settings["SWIFT_OPTIMIZATION_LEVEL"] = "-Onone"

end

**Comment by jcampbell05** [comment]
Hmm I I wonder if there is some subtle behaviour with the 

`target.debug_configuration :Debug do |configuration|`

In theory it should return the same configuration but I wonder if there is a regression where it makes a new configuration or returns a copy of the configuration but doesn't modify the actual configuration itself. I'll dig into this.

**Comment by maximkhatskevich** [comment]
Yes, please. If it's something that's hard (or takes long time) to fix - it would be good to know what is the latest previous version of Xcake that has not that issues and still safe to use with latest Xcode. Thanks!

**Comment by jcampbell05** [comment]
@maximkhatskevich Looking into this right now, trying to narrow down the precise issue so I can implement a unit test to fix this.

**Comment by maximkhatskevich** [comment]
thank you! Sure, see attached
[Cakefile.txt](https://github.com/jcampbell05/xcake/files/300168/Cakefile.txt)

**Comment by jcampbell05** [comment]
@maximkhatskevich Just ran it on my system and it seems to pick the correct build settings up can you tell me which version of xcake you are using ?

Just run `xcake --version`

**Comment by maximkhatskevich** [comment]
0.6.18

**Comment by maximkhatskevich** [comment]
Xcode 7.3.1

**Comment by maximkhatskevich** [comment]
Btw, I run via Fastlane, try that approach too, maybe it's fastlane plugin issue? I'll try without fastlane and let you know.

**Comment by maximkhatskevich** [comment]
Fastlane does not change anything, it still does not work. Still ignores properties set to a specific configuration, only flags that set inside "target.all_configurations.each" block are presented

**Comment by maximkhatskevich** [comment]
It definitely gives me a copy of configuration when I access it like this: "target.debug_configuration :Staging do |configuration|" and never apply made changes to real project configurations. But I think I found a solution/workaround - inside "target.all_configurations.each" block use "if configuration.name == 'MyConfiguration1' do <apply any attributes only for this configuration> end".

**Comment by jcampbell05** [comment]
Ohh weird, so the all_configurations works.

**Comment by maximkhatskevich** [comment]
Yes, "all_configurations" was working all the time. After I complete experiments with my Cakefile - I'll definitely update documentation for the project, will put real world comprehensive example Cakefile with comments. Hope fully will find time for this this weekend. So I'm good so far, don't worry. Thank you for your help - your assumption about "copy that never apply settings back to real configurations" was right and helped me find this solution. I appreciate your help, man!

**Comment by jcampbell05** [comment]
@maximkhatskevich  no problem, thank you for using this tool and putting up with the bugs you find. I promise I will find them and I will destroy them 💥 !
