### ISSUE TITLE
Implement XCConfig capbabilites to Xcake

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#79]
Possibly as a plugin ?

**Comment by jcampbell05** [comment]
Will do this if requested or needed by any users.

**Comment by walpoletim-bjss** [comment]
have just come across xcake - Its fantastic.  We however use xcconfig files to configure or projects to being able to have xccake spitting out xcconfig files wold be amazing

Thanks

**Comment by jcampbell05** [comment]
@walpoletim-bjss thanks for the kind words :) I've reopened this so I can start planning it.
