### ISSUE TITLE
project.project_name doesn't seem to exist anymore?

### ISSUE THREAD

**Issue by brennantaylor** [jcampbell05/xcake#81]
It appears to be `project.name` but the Cakefile from `xcake init` still uses `project_name` and all the documentation still refers to `project.name`

**Comment by jcampbell05** [comment]
Good catch! I will make sure to update this.

**Comment by brennantaylor** [comment]
@jcampbell05 I wanted to mention thanks for this project it's helping me alot!

**Comment by jcampbell05** [comment]
@brennantaylor thank you :) keep filling these issues these are a really big help!
