### ISSUE TITLE
How do we include files (e.g. they are in the project file picker) but not include them in the compiled sources?

### ISSUE THREAD

**Issue by colinta** [jcampbell05/xcake#92]
e.g. `Info.plist`?  Every time I compile I have to un-include it from the "Target Membership" settings.

**Comment by colinta** [comment]
Ahh ok, `CopyResourcesFileReferenceInstaller` handles this.  And there are *some* `plist` files that you might want to include in the bundle, so just returning `false` based on the extension might not cut it.  We would need to include the target (?) in `can_install_node`, and check to see if the node in question *is* the `settings['INFOPLIST_FILE']`

**Comment by colinta** [comment]
(not just the target - the specific configuration, since `INFOPLIST_FILE` is a per-configuration setting.

**Comment by jcampbell05** [comment]
@colinta So basically we shouldn't be including the Info.plists that may be used for the App Information? Have I got that right ?

**Comment by colinta** [comment]
Ideally yes, but I couldn't figure out a simple way to differentiate it, and it's a minor issue. If you think it's possible, we can reopen and work on it!

Do you include the Support folder in the included sources? That's how I got to this point. Info.plist *doesn't* have to be in the Xcode project in order to be used by the compiler, but of course I like having it in the project.

**Comment by jcampbell05** [comment]
@colinta I currently include all files under the folder with the same name as the Application Target, so I would imagine that would include the Support folder.

It should be possible to have it in the project but not added to the build phase. I'm not sure `0.6` has the infrastructure to do this but I am also working on refactoring the file installer system for `0.7` to simplify cases like this as there is a lot that could be simplified with how files are handled. :)

**Comment by jcampbell05** [comment]
I'll create a markdown document on how I envision it could work if you're open to it!

**Comment by colinta** [comment]
Definitely!  Would love to read about it, and hopefully I can throw in a thought or two. :-)

**Comment by jcampbell05** [comment]
@colinta  So I have a rough outline of the goals for `0.7.0` here and how we will implement the new file system to fix things like these.

https://github.com/jcampbell05/xcake/issues/94

Let me know if you think it's missing any details, we can flesh it out as it's built.

**Comment by maximkhatskevich** [comment]
Hey guys. Just wanted to share with you my approach on this subject. I keep all source files in one folder (with subfolders, of course) - "Src". Then I put all resources (like assets catalog, fonts, etc.) under "Res" folder. Then I point to these folders in the "include_files" property. But I keep all "Info.plist" files (for app target, for unit tests targets, etc.) under separate folder called "Info", which is on the same level as "Src" and "Res", so I do not care if Xcake can recognize that info plist files properly or not - it just have no chances to include them into target, while I still can easily reference to them when set target info plist properties. This also brings more clarity on project files organization. Hope that makes sense for you.

**Comment by jcampbell05** [comment]
@maximkhatskevich  Could be interesting to have a write up about that approach. At some point I want to build a tool for setting up a new project which could have structures like that.

If we still wanted to solve this problem in Ccake then:

We changed the behaviour in Xcake for header files so in the future you will have to explicitly have them included. In theory we could do something like that with plists where if you set a plist as being a "info" plist then Xcake could exclude it automatically for you.

**Comment by maximkhatskevich** [comment]
So you want me to include that idea as recommendation somewhere in Xcake Readme or Cakefile documentation? @jcampbell05

**Comment by jcampbell05** [comment]
@maximkhatskevich  maybe documentation :)

**Comment by maximkhatskevich** [comment]
Okay!

**Comment by maximkhatskevich** [comment]
@jcampbell05 my approach on project internal structure is clear visible/explained in the sample Cakefile for an app target, so no extra explanations are needed anywhere else, I think.

**Comment by jcampbell05** [comment]
:) great, SGTM
