### ISSUE TITLE
Xcake 0.7.X Roadmap

### ISSUE THREAD

**Issue by jcampbell05** [jcampbell05/xcake#94]
Here are at 6 Months after Xcake's release and we have just pushed the last version of `0.6.x`

This has been our most successful release ever, Spanning 25 minor versions, 6 Months and over 1,000 Downloads. We've had our most number of external contributions to this version as well.

In this series we overhauled the entire generator system in order to easily control what happens in each order via a dependency graph, reduced them so that each generator handles a small part of the project to increase testability and introduced a context object to remove many of the hacks used to get additional information needed during generation for the project (For example when setting up XCConfig Files).

However there comes a time where the creaks start to show and I believe we have reached this with `0.6.x`. So what's planned for `0.7.0`:

## New File Reference And Build Phase Generators

This will be the large portion of the work, the system for creating file references and creating build phases is fragmented and handled by multiple classes. The goal for us will be similar to the recent refactor of the generator system:

- Break the system up into smaller components.
- Abstract them in a way so each phase only needs to do the minimum to achieve it's goal and it can be reusable by other parts of the code.
- Simplify the system so they no longer have to use hacks or complicated logic.

So how will we achieve this with `0.7`, well let's first look at the issues with the current system:

- File References outside of `include_files` rely on hacks or duplicating behaviour (i.e for XCConfig or Info.plist).
- Adding support for Variant Groups (i.e for Localised files) relied again on hacks or duplicate behaviour.
- The file installers rely on a few tricks to make sure they add the files to the correct build phases in the right order which could be simplified - they both classify and install files which is two concerns.
- The user can't define their own build phases (Except run script)  and any code inside of the system has to duplicate the code to create their own.
- It can be difficult to get an existing File Reference for a file.
- The code for creating Groups in the project has grown very complex. (i.e to handle variant groups and to handle setting the correct target for a group).

So how can we resolve these issues? Well we will break these down into phases and individual generators, so here are the phases in order:

#### Phase 1: File Reference Generator 

- Add Groups / Variant Groups with correct path so that it opens in Xcode, Have right Name and Target.
- Add File Reference to project

#### Phase 2: Run Any Generators That May Create Build Phases.

- For example we create build phases to embed a watch app (Although this could be potentially moved to being created in the DSL).

#### Phase 3: File Reference Build Phase Association Generator

- Collect all files in `include_files` which aren't referenced in another build phase.
- Use File Classifiers to figure out which build phase they belong to.
- Tweak DSL so that they are added to a build phase.
- This could potentially be done as part of the DSL instead.

#### Phase 4: Build Phase Generator

- Take Build Phases defined in DSL, Create Them and add any File References they refer to. (DSL will be extended to allow users to define all types of build phases)

Feature-wise this will:

- Simplify way groups and files are added.
- Allow files to be added easily from other sources not just `include_files`.
- Simplify way build phases are created, open it up to other generators and the user.
- Extend build phase types that can be created by the user in the DSL.
- Potentially Fix https://github.com/jcampbell05/xcake/issues/92

## Aggregate Targets

Add the ability to specify aggregate targets, this would involve creating a new type of target since Xcodproj uses a different class for this.

## UI Tests

Add the ability to implement UI Tests, this will involve extending support for multiple testing targets for each target.

## Other Goals

To resolve all outstanding Github Issues before `0.8.0` and publish some documents on the internal structure of Xcake to help contributors out :)

**Comment by colinta** [comment]
Sounds like a great direction.

The Ello app also needs *Share Extension* target support, so if that's easy to accomplish during this refactor, it would make it easier for that project to adopt xcake!

**Comment by jcampbell05** [comment]
@colinta I can look at how Xcake pull's that off. I'm sure we should be able to do it since the Watch app is already an extensions and Xcake already supports that.

**Comment by jcampbell05** [comment]
@colinta  so the initial file installer refactor has been implemented which simplifies the system. One side effect is xcode now selects the right groups when adding to a group

I think next I'll work on adding Extensions, UI Testing and Aggregate Testing Support.

After some testing I think `0.7`will be good to go.

**Comment by colinta** [comment]
You've been busy! I'll try out what you've uploaded so far.

**Comment by jcampbell05** [comment]
@colinta Great, any feedback or regressions let me know. It's not pushed yet so you should be able to install from `master`.

**Comment by jcampbell05** [comment]
Should be releasing this week @maximkhatskevich  @colinta

**Comment by jcampbell05** [comment]
0.7 is released, just need to get a test passing for https://github.com/jcampbell05/xcake/pull/103 @maximkhatskevich - Will push this in a 7.1

**Comment by maximkhatskevich** [comment]
Great! Thanks, dude!

**Comment by jcampbell05** [comment]
@maximkhatskevich  UI Tests should be pushed in 0.7.1 :) Will close this and start working on all the issues you've raised :)
